// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_account_data.proto
// Protobuf C++ Version: 5.29.2

#include "pch.h"

#include "user_account_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr UserAccountDataRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserAccountDataRequest::UserAccountDataRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserAccountDataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserAccountDataRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserAccountDataRequestDefaultTypeInternal() {}
  union {
    UserAccountDataRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserAccountDataRequestDefaultTypeInternal _UserAccountDataRequest_default_instance_;

inline constexpr Balance::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : asset_symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        free_amount_{0},
        locked_amount_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Balance::Balance(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BalanceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BalanceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BalanceDefaultTypeInternal() {}
  union {
    Balance _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BalanceDefaultTypeInternal _Balance_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR UserAccountDataResponse_BalancesEntry_DoNotUse::UserAccountDataResponse_BalancesEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : UserAccountDataResponse_BalancesEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : UserAccountDataResponse_BalancesEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UserAccountDataResponse_BalancesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserAccountDataResponse_BalancesEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserAccountDataResponse_BalancesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    UserAccountDataResponse_BalancesEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserAccountDataResponse_BalancesEntry_DoNotUseDefaultTypeInternal _UserAccountDataResponse_BalancesEntry_DoNotUse_default_instance_;

inline constexpr UserAccountDataResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : balances_{},
        user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        maker_commission_{0u},
        taker_commission_{0u},
        buyer_commission_{0u},
        seller_commission_{0u},
        update_time_{::uint64_t{0u}},
        stable_coin_amount_{0},
        can_trade_{false},
        can_withdraw_{false},
        can_deposit_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserAccountDataResponse::UserAccountDataResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserAccountDataResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserAccountDataResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserAccountDataResponseDefaultTypeInternal() {}
  union {
    UserAccountDataResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserAccountDataResponseDefaultTypeInternal _UserAccountDataResponse_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_user_5faccount_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_user_5faccount_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_user_5faccount_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Balance, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Balance, _impl_.asset_symbol_),
        PROTOBUF_FIELD_OFFSET(::Balance, _impl_.free_amount_),
        PROTOBUF_FIELD_OFFSET(::Balance, _impl_.locked_amount_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::UserAccountDataRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::UserAccountDataRequest, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse_BalancesEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.maker_commission_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.taker_commission_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.buyer_commission_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.seller_commission_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.update_time_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.can_trade_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.can_withdraw_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.can_deposit_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.stable_coin_amount_),
        PROTOBUF_FIELD_OFFSET(::UserAccountDataResponse, _impl_.balances_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Balance)},
        {11, -1, -1, sizeof(::UserAccountDataRequest)},
        {20, 30, -1, sizeof(::UserAccountDataResponse_BalancesEntry_DoNotUse)},
        {32, -1, -1, sizeof(::UserAccountDataResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Balance_default_instance_._instance,
    &::_UserAccountDataRequest_default_instance_._instance,
    &::_UserAccountDataResponse_BalancesEntry_DoNotUse_default_instance_._instance,
    &::_UserAccountDataResponse_default_instance_._instance,
};
const char descriptor_table_protodef_user_5faccount_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027user_account_data.proto\"K\n\007Balance\022\024\n\014"
    "asset_symbol\030\001 \001(\t\022\023\n\013free_amount\030\002 \001(\001\022"
    "\025\n\rlocked_amount\030\003 \001(\001\")\n\026UserAccountDat"
    "aRequest\022\017\n\007user_id\030\001 \001(\t\"\367\002\n\027UserAccoun"
    "tDataResponse\022\017\n\007user_id\030\001 \001(\t\022\030\n\020maker_"
    "commission\030\002 \001(\r\022\030\n\020taker_commission\030\003 \001"
    "(\r\022\030\n\020buyer_commission\030\004 \001(\r\022\031\n\021seller_c"
    "ommission\030\005 \001(\r\022\023\n\013update_time\030\006 \001(\004\022\021\n\t"
    "can_trade\030\007 \001(\010\022\024\n\014can_withdraw\030\010 \001(\010\022\023\n"
    "\013can_deposit\030\t \001(\010\022\032\n\022stable_coin_amount"
    "\030\n \001(\001\0228\n\010balances\030\013 \003(\0132&.UserAccountDa"
    "taResponse.BalancesEntry\0329\n\rBalancesEntr"
    "y\022\013\n\003key\030\001 \001(\t\022\027\n\005value\030\002 \001(\0132\010.Balance:"
    "\0028\0012]\n\022UserAccountService\022G\n\022GetUserAcco"
    "untData\022\027.UserAccountDataRequest\032\030.UserA"
    "ccountDataResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_user_5faccount_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_user_5faccount_5fdata_2eproto = {
    false,
    false,
    626,
    descriptor_table_protodef_user_5faccount_5fdata_2eproto,
    "user_account_data.proto",
    &descriptor_table_user_5faccount_5fdata_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_user_5faccount_5fdata_2eproto::offsets,
    file_level_enum_descriptors_user_5faccount_5fdata_2eproto,
    file_level_service_descriptors_user_5faccount_5fdata_2eproto,
};
// ===================================================================

class Balance::_Internal {
 public:
};

Balance::Balance(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Balance)
}
inline PROTOBUF_NDEBUG_INLINE Balance::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Balance& from_msg)
      : asset_symbol_(arena, from.asset_symbol_),
        _cached_size_{0} {}

Balance::Balance(
    ::google::protobuf::Arena* arena,
    const Balance& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Balance* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, free_amount_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, free_amount_),
           offsetof(Impl_, locked_amount_) -
               offsetof(Impl_, free_amount_) +
               sizeof(Impl_::locked_amount_));

  // @@protoc_insertion_point(copy_constructor:Balance)
}
inline PROTOBUF_NDEBUG_INLINE Balance::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : asset_symbol_(arena),
        _cached_size_{0} {}

inline void Balance::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, free_amount_),
           0,
           offsetof(Impl_, locked_amount_) -
               offsetof(Impl_, free_amount_) +
               sizeof(Impl_::locked_amount_));
}
Balance::~Balance() {
  // @@protoc_insertion_point(destructor:Balance)
  SharedDtor(*this);
}
inline void Balance::SharedDtor(MessageLite& self) {
  Balance& this_ = static_cast<Balance&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.asset_symbol_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Balance::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Balance(arena);
}
constexpr auto Balance::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Balance),
                                            alignof(Balance));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Balance::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Balance_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Balance::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Balance>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Balance::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Balance>(), &Balance::ByteSizeLong,
            &Balance::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Balance, _impl_._cached_size_),
        false,
    },
    &Balance::kDescriptorMethods,
    &descriptor_table_user_5faccount_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Balance::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 28, 2> Balance::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Balance>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string asset_symbol = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Balance, _impl_.asset_symbol_)}},
    // double free_amount = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Balance, _impl_.free_amount_)}},
    // double locked_amount = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Balance, _impl_.locked_amount_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string asset_symbol = 1;
    {PROTOBUF_FIELD_OFFSET(Balance, _impl_.asset_symbol_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double free_amount = 2;
    {PROTOBUF_FIELD_OFFSET(Balance, _impl_.free_amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double locked_amount = 3;
    {PROTOBUF_FIELD_OFFSET(Balance, _impl_.locked_amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\7\14\0\0\0\0\0\0"
    "Balance"
    "asset_symbol"
  }},
};

PROTOBUF_NOINLINE void Balance::Clear() {
// @@protoc_insertion_point(message_clear_start:Balance)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.asset_symbol_.ClearToEmpty();
  ::memset(&_impl_.free_amount_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.locked_amount_) -
      reinterpret_cast<char*>(&_impl_.free_amount_)) + sizeof(_impl_.locked_amount_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Balance::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Balance& this_ = static_cast<const Balance&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Balance::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Balance& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Balance)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string asset_symbol = 1;
          if (!this_._internal_asset_symbol().empty()) {
            const std::string& _s = this_._internal_asset_symbol();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Balance.asset_symbol");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double free_amount = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_free_amount()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_free_amount(), target);
          }

          // double locked_amount = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_locked_amount()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_locked_amount(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Balance)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Balance::ByteSizeLong(const MessageLite& base) {
          const Balance& this_ = static_cast<const Balance&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Balance::ByteSizeLong() const {
          const Balance& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Balance)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string asset_symbol = 1;
            if (!this_._internal_asset_symbol().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_asset_symbol());
            }
            // double free_amount = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_free_amount()) != 0) {
              total_size += 9;
            }
            // double locked_amount = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_locked_amount()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Balance::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Balance*>(&to_msg);
  auto& from = static_cast<const Balance&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Balance)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_asset_symbol().empty()) {
    _this->_internal_set_asset_symbol(from._internal_asset_symbol());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_free_amount()) != 0) {
    _this->_impl_.free_amount_ = from._impl_.free_amount_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_locked_amount()) != 0) {
    _this->_impl_.locked_amount_ = from._impl_.locked_amount_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Balance::CopyFrom(const Balance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Balance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Balance::InternalSwap(Balance* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.asset_symbol_, &other->_impl_.asset_symbol_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Balance, _impl_.locked_amount_)
      + sizeof(Balance::_impl_.locked_amount_)
      - PROTOBUF_FIELD_OFFSET(Balance, _impl_.free_amount_)>(
          reinterpret_cast<char*>(&_impl_.free_amount_),
          reinterpret_cast<char*>(&other->_impl_.free_amount_));
}

::google::protobuf::Metadata Balance::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserAccountDataRequest::_Internal {
 public:
};

UserAccountDataRequest::UserAccountDataRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UserAccountDataRequest)
}
inline PROTOBUF_NDEBUG_INLINE UserAccountDataRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::UserAccountDataRequest& from_msg)
      : user_id_(arena, from.user_id_),
        _cached_size_{0} {}

UserAccountDataRequest::UserAccountDataRequest(
    ::google::protobuf::Arena* arena,
    const UserAccountDataRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserAccountDataRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:UserAccountDataRequest)
}
inline PROTOBUF_NDEBUG_INLINE UserAccountDataRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        _cached_size_{0} {}

inline void UserAccountDataRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserAccountDataRequest::~UserAccountDataRequest() {
  // @@protoc_insertion_point(destructor:UserAccountDataRequest)
  SharedDtor(*this);
}
inline void UserAccountDataRequest::SharedDtor(MessageLite& self) {
  UserAccountDataRequest& this_ = static_cast<UserAccountDataRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserAccountDataRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserAccountDataRequest(arena);
}
constexpr auto UserAccountDataRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserAccountDataRequest),
                                            alignof(UserAccountDataRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserAccountDataRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserAccountDataRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserAccountDataRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserAccountDataRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserAccountDataRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserAccountDataRequest>(), &UserAccountDataRequest::ByteSizeLong,
            &UserAccountDataRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserAccountDataRequest, _impl_._cached_size_),
        false,
    },
    &UserAccountDataRequest::kDescriptorMethods,
    &descriptor_table_user_5faccount_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserAccountDataRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> UserAccountDataRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::UserAccountDataRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataRequest, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataRequest, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\7\0\0\0\0\0\0"
    "UserAccountDataRequest"
    "user_id"
  }},
};

PROTOBUF_NOINLINE void UserAccountDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:UserAccountDataRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserAccountDataRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserAccountDataRequest& this_ = static_cast<const UserAccountDataRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserAccountDataRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserAccountDataRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:UserAccountDataRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UserAccountDataRequest.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:UserAccountDataRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserAccountDataRequest::ByteSizeLong(const MessageLite& base) {
          const UserAccountDataRequest& this_ = static_cast<const UserAccountDataRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserAccountDataRequest::ByteSizeLong() const {
          const UserAccountDataRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:UserAccountDataRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserAccountDataRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserAccountDataRequest*>(&to_msg);
  auto& from = static_cast<const UserAccountDataRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UserAccountDataRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserAccountDataRequest::CopyFrom(const UserAccountDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UserAccountDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserAccountDataRequest::InternalSwap(UserAccountDataRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
}

::google::protobuf::Metadata UserAccountDataRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              UserAccountDataResponse_BalancesEntry_DoNotUse::UserAccountDataResponse_BalancesEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              UserAccountDataResponse_BalancesEntry_DoNotUse::UserAccountDataResponse_BalancesEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              UserAccountDataResponse_BalancesEntry_DoNotUse::UserAccountDataResponse_BalancesEntry_DoNotUse() : SuperType() {}
              UserAccountDataResponse_BalancesEntry_DoNotUse::UserAccountDataResponse_BalancesEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* UserAccountDataResponse_BalancesEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) UserAccountDataResponse_BalancesEntry_DoNotUse(arena);
              }
              constexpr auto UserAccountDataResponse_BalancesEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserAccountDataResponse_BalancesEntry_DoNotUse),
                                                          alignof(UserAccountDataResponse_BalancesEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull UserAccountDataResponse_BalancesEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_UserAccountDataResponse_BalancesEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &UserAccountDataResponse_BalancesEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<UserAccountDataResponse_BalancesEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &UserAccountDataResponse_BalancesEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &UserAccountDataResponse_BalancesEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &UserAccountDataResponse_BalancesEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_user_5faccount_5fdata_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* UserAccountDataResponse_BalancesEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 49, 2> UserAccountDataResponse_BalancesEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::UserAccountDataResponse_BalancesEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Balance value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Balance value = 2;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse_BalancesEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Balance>()},
  }}, {{
    "\45\3\0\0\0\0\0\0"
    "UserAccountDataResponse.BalancesEntry"
    "key"
  }},
};

// ===================================================================

class UserAccountDataResponse::_Internal {
 public:
};

UserAccountDataResponse::UserAccountDataResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UserAccountDataResponse)
}
inline PROTOBUF_NDEBUG_INLINE UserAccountDataResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::UserAccountDataResponse& from_msg)
      : balances_{visibility, arena, from.balances_},
        user_id_(arena, from.user_id_),
        _cached_size_{0} {}

UserAccountDataResponse::UserAccountDataResponse(
    ::google::protobuf::Arena* arena,
    const UserAccountDataResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserAccountDataResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, maker_commission_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, maker_commission_),
           offsetof(Impl_, can_deposit_) -
               offsetof(Impl_, maker_commission_) +
               sizeof(Impl_::can_deposit_));

  // @@protoc_insertion_point(copy_constructor:UserAccountDataResponse)
}
inline PROTOBUF_NDEBUG_INLINE UserAccountDataResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : balances_{visibility, arena},
        user_id_(arena),
        _cached_size_{0} {}

inline void UserAccountDataResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, maker_commission_),
           0,
           offsetof(Impl_, can_deposit_) -
               offsetof(Impl_, maker_commission_) +
               sizeof(Impl_::can_deposit_));
}
UserAccountDataResponse::~UserAccountDataResponse() {
  // @@protoc_insertion_point(destructor:UserAccountDataResponse)
  SharedDtor(*this);
}
inline void UserAccountDataResponse::SharedDtor(MessageLite& self) {
  UserAccountDataResponse& this_ = static_cast<UserAccountDataResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserAccountDataResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserAccountDataResponse(arena);
}
constexpr auto UserAccountDataResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.balances_) +
          decltype(UserAccountDataResponse::_impl_.balances_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.balances_) +
          decltype(UserAccountDataResponse::_impl_.balances_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(UserAccountDataResponse), alignof(UserAccountDataResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&UserAccountDataResponse::PlacementNew_,
                                 sizeof(UserAccountDataResponse),
                                 alignof(UserAccountDataResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserAccountDataResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserAccountDataResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserAccountDataResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserAccountDataResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserAccountDataResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserAccountDataResponse>(), &UserAccountDataResponse::ByteSizeLong,
            &UserAccountDataResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_._cached_size_),
        false,
    },
    &UserAccountDataResponse::kDescriptorMethods,
    &descriptor_table_user_5faccount_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserAccountDataResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 2, 55, 2> UserAccountDataResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::UserAccountDataResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.user_id_)}},
    // uint32 maker_commission = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserAccountDataResponse, _impl_.maker_commission_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.maker_commission_)}},
    // uint32 taker_commission = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserAccountDataResponse, _impl_.taker_commission_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.taker_commission_)}},
    // uint32 buyer_commission = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserAccountDataResponse, _impl_.buyer_commission_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.buyer_commission_)}},
    // uint32 seller_commission = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserAccountDataResponse, _impl_.seller_commission_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.seller_commission_)}},
    // uint64 update_time = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UserAccountDataResponse, _impl_.update_time_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.update_time_)}},
    // bool can_trade = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserAccountDataResponse, _impl_.can_trade_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_trade_)}},
    // bool can_withdraw = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserAccountDataResponse, _impl_.can_withdraw_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_withdraw_)}},
    // bool can_deposit = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserAccountDataResponse, _impl_.can_deposit_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_deposit_)}},
    // double stable_coin_amount = 10;
    {::_pbi::TcParser::FastF64S1,
     {81, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.stable_coin_amount_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 maker_commission = 2;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.maker_commission_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 taker_commission = 3;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.taker_commission_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 buyer_commission = 4;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.buyer_commission_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 seller_commission = 5;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.seller_commission_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 update_time = 6;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.update_time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bool can_trade = 7;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_trade_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_withdraw = 8;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_withdraw_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_deposit = 9;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_deposit_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // double stable_coin_amount = 10;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.stable_coin_amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // map<string, .Balance> balances = 11;
    {PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.balances_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(UserAccountDataResponse()._impl_.balances_)>(
        1, 0, 0, 9,
        11)},
    {::_pbi::TcParser::GetTable<::Balance>()},
  }}, {{
    "\27\7\0\0\0\0\0\0\0\0\0\10\0\0\0\0"
    "UserAccountDataResponse"
    "user_id"
    "balances"
  }},
};

PROTOBUF_NOINLINE void UserAccountDataResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:UserAccountDataResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.balances_.Clear();
  _impl_.user_id_.ClearToEmpty();
  ::memset(&_impl_.maker_commission_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.can_deposit_) -
      reinterpret_cast<char*>(&_impl_.maker_commission_)) + sizeof(_impl_.can_deposit_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserAccountDataResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserAccountDataResponse& this_ = static_cast<const UserAccountDataResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserAccountDataResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserAccountDataResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:UserAccountDataResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_id = 1;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UserAccountDataResponse.user_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // uint32 maker_commission = 2;
          if (this_._internal_maker_commission() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_maker_commission(), target);
          }

          // uint32 taker_commission = 3;
          if (this_._internal_taker_commission() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_taker_commission(), target);
          }

          // uint32 buyer_commission = 4;
          if (this_._internal_buyer_commission() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_buyer_commission(), target);
          }

          // uint32 seller_commission = 5;
          if (this_._internal_seller_commission() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                5, this_._internal_seller_commission(), target);
          }

          // uint64 update_time = 6;
          if (this_._internal_update_time() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                6, this_._internal_update_time(), target);
          }

          // bool can_trade = 7;
          if (this_._internal_can_trade() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_can_trade(), target);
          }

          // bool can_withdraw = 8;
          if (this_._internal_can_withdraw() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                8, this_._internal_can_withdraw(), target);
          }

          // bool can_deposit = 9;
          if (this_._internal_can_deposit() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                9, this_._internal_can_deposit(), target);
          }

          // double stable_coin_amount = 10;
          if (::absl::bit_cast<::uint64_t>(this_._internal_stable_coin_amount()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                10, this_._internal_stable_coin_amount(), target);
          }

          // map<string, .Balance> balances = 11;
          if (!this_._internal_balances().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::Balance>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::Balance,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_MESSAGE>;
            const auto& field = this_._internal_balances();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    11, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UserAccountDataResponse.balances");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    11, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UserAccountDataResponse.balances");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:UserAccountDataResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserAccountDataResponse::ByteSizeLong(const MessageLite& base) {
          const UserAccountDataResponse& this_ = static_cast<const UserAccountDataResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserAccountDataResponse::ByteSizeLong() const {
          const UserAccountDataResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:UserAccountDataResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, .Balance> balances = 11;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_balances_size());
              for (const auto& entry : this_._internal_balances()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::Balance,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string user_id = 1;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // uint32 maker_commission = 2;
            if (this_._internal_maker_commission() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_maker_commission());
            }
            // uint32 taker_commission = 3;
            if (this_._internal_taker_commission() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_taker_commission());
            }
            // uint32 buyer_commission = 4;
            if (this_._internal_buyer_commission() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_buyer_commission());
            }
            // uint32 seller_commission = 5;
            if (this_._internal_seller_commission() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_seller_commission());
            }
            // uint64 update_time = 6;
            if (this_._internal_update_time() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_update_time());
            }
            // double stable_coin_amount = 10;
            if (::absl::bit_cast<::uint64_t>(this_._internal_stable_coin_amount()) != 0) {
              total_size += 9;
            }
            // bool can_trade = 7;
            if (this_._internal_can_trade() != 0) {
              total_size += 2;
            }
            // bool can_withdraw = 8;
            if (this_._internal_can_withdraw() != 0) {
              total_size += 2;
            }
            // bool can_deposit = 9;
            if (this_._internal_can_deposit() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserAccountDataResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserAccountDataResponse*>(&to_msg);
  auto& from = static_cast<const UserAccountDataResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UserAccountDataResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.balances_.MergeFrom(from._impl_.balances_);
  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_maker_commission() != 0) {
    _this->_impl_.maker_commission_ = from._impl_.maker_commission_;
  }
  if (from._internal_taker_commission() != 0) {
    _this->_impl_.taker_commission_ = from._impl_.taker_commission_;
  }
  if (from._internal_buyer_commission() != 0) {
    _this->_impl_.buyer_commission_ = from._impl_.buyer_commission_;
  }
  if (from._internal_seller_commission() != 0) {
    _this->_impl_.seller_commission_ = from._impl_.seller_commission_;
  }
  if (from._internal_update_time() != 0) {
    _this->_impl_.update_time_ = from._impl_.update_time_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_stable_coin_amount()) != 0) {
    _this->_impl_.stable_coin_amount_ = from._impl_.stable_coin_amount_;
  }
  if (from._internal_can_trade() != 0) {
    _this->_impl_.can_trade_ = from._impl_.can_trade_;
  }
  if (from._internal_can_withdraw() != 0) {
    _this->_impl_.can_withdraw_ = from._impl_.can_withdraw_;
  }
  if (from._internal_can_deposit() != 0) {
    _this->_impl_.can_deposit_ = from._impl_.can_deposit_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserAccountDataResponse::CopyFrom(const UserAccountDataResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UserAccountDataResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserAccountDataResponse::InternalSwap(UserAccountDataResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.balances_.InternalSwap(&other->_impl_.balances_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.can_deposit_)
      + sizeof(UserAccountDataResponse::_impl_.can_deposit_)
      - PROTOBUF_FIELD_OFFSET(UserAccountDataResponse, _impl_.maker_commission_)>(
          reinterpret_cast<char*>(&_impl_.maker_commission_),
          reinterpret_cast<char*>(&other->_impl_.maker_commission_));
}

::google::protobuf::Metadata UserAccountDataResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_user_5faccount_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
