// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_trade_profile.proto

#include "pch.h"

#include "user_trade_profile.pb.h"
#include "user_trade_profile.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace usertradeprofile {

static const char* TradeService_method_names[] = {
  "/usertradeprofile.TradeService/UpdateUserTradeProfile",
};

std::unique_ptr< TradeService::Stub> TradeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TradeService::Stub> stub(new TradeService::Stub(channel, options));
  return stub;
}

TradeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UpdateUserTradeProfile_(TradeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TradeService::Stub::UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::usertradeprofile::UpdateUserTradeProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateUserTradeProfile_, context, request, response);
}

void TradeService::Stub::async::UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserTradeProfile_, context, request, response, std::move(f));
}

void TradeService::Stub::async::UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserTradeProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>* TradeService::Stub::PrepareAsyncUpdateUserTradeProfileRaw(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::usertradeprofile::UpdateUserTradeProfileResponse, ::usertradeprofile::UpdateUserTradeProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateUserTradeProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>* TradeService::Stub::AsyncUpdateUserTradeProfileRaw(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateUserTradeProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

TradeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradeService::Service, ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::usertradeprofile::UpdateUserTradeProfileRequest* req,
             ::usertradeprofile::UpdateUserTradeProfileResponse* resp) {
               return service->UpdateUserTradeProfile(ctx, req, resp);
             }, this)));
}

TradeService::Service::~Service() {
}

::grpc::Status TradeService::Service::UpdateUserTradeProfile(::grpc::ServerContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace usertradeprofile

