// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_future_account_data.proto
#ifndef GRPC_user_5ffuture_5faccount_5fdata_2eproto__INCLUDED
#define GRPC_user_5ffuture_5faccount_5fdata_2eproto__INCLUDED

#include "user_future_account_data.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace futureaccount {

class UserAccountService final {
 public:
  static constexpr char const* service_full_name() {
    return "futureaccount.UserAccountService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::futureaccount::GetUserFutureAccountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::futureaccount::GetUserFutureAccountResponse>> AsyncGetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::futureaccount::GetUserFutureAccountResponse>>(AsyncGetUserFutureAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::futureaccount::GetUserFutureAccountResponse>> PrepareAsyncGetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::futureaccount::GetUserFutureAccountResponse>>(PrepareAsyncGetUserFutureAccountRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::futureaccount::GetUserFutureAccountResponse>* AsyncGetUserFutureAccountRaw(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::futureaccount::GetUserFutureAccountResponse>* PrepareAsyncGetUserFutureAccountRaw(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::futureaccount::GetUserFutureAccountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>> AsyncGetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>>(AsyncGetUserFutureAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>> PrepareAsyncGetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>>(PrepareAsyncGetUserFutureAccountRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response, std::function<void(::grpc::Status)>) override;
      void GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>* AsyncGetUserFutureAccountRaw(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>* PrepareAsyncGetUserFutureAccountRaw(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUserFutureAccount_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserFutureAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUserFutureAccount() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUserFutureAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserFutureAccount(::grpc::ServerContext* context, ::futureaccount::GetUserFutureAccountRequest* request, ::grpc::ServerAsyncResponseWriter< ::futureaccount::GetUserFutureAccountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUserFutureAccount<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUserFutureAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUserFutureAccount() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response) { return this->GetUserFutureAccount(context, request, response); }));}
    void SetMessageAllocatorFor_GetUserFutureAccount(
        ::grpc::MessageAllocator< ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUserFutureAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserFutureAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUserFutureAccount<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUserFutureAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUserFutureAccount() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUserFutureAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUserFutureAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUserFutureAccount() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUserFutureAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserFutureAccount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUserFutureAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUserFutureAccount() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUserFutureAccount(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUserFutureAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserFutureAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserFutureAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUserFutureAccount() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse>* streamer) {
                       return this->StreamedGetUserFutureAccount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUserFutureAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserFutureAccount(::grpc::ServerContext* /*context*/, const ::futureaccount::GetUserFutureAccountRequest* /*request*/, ::futureaccount::GetUserFutureAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserFutureAccount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::futureaccount::GetUserFutureAccountRequest,::futureaccount::GetUserFutureAccountResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUserFutureAccount<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUserFutureAccount<Service > StreamedService;
};

}  // namespace futureaccount


#endif  // GRPC_user_5ffuture_5faccount_5fdata_2eproto__INCLUDED
