// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_trade_profile.proto
// Protobuf C++ Version: 5.29.2

#include "pch.h"

#include "user_trade_profile.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace usertradeprofile {

inline constexpr UpdateUserTradeProfileResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateUserTradeProfileResponse::UpdateUserTradeProfileResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateUserTradeProfileResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateUserTradeProfileResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateUserTradeProfileResponseDefaultTypeInternal() {}
  union {
    UpdateUserTradeProfileResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateUserTradeProfileResponseDefaultTypeInternal _UpdateUserTradeProfileResponse_default_instance_;

inline constexpr UpdateUserTradeProfileRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_account_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        leverage_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateUserTradeProfileRequest::UpdateUserTradeProfileRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateUserTradeProfileRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateUserTradeProfileRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateUserTradeProfileRequestDefaultTypeInternal() {}
  union {
    UpdateUserTradeProfileRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateUserTradeProfileRequestDefaultTypeInternal _UpdateUserTradeProfileRequest_default_instance_;
}  // namespace usertradeprofile
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_user_5ftrade_5fprofile_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_user_5ftrade_5fprofile_2eproto = nullptr;
const ::uint32_t
    TableStruct_user_5ftrade_5fprofile_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::usertradeprofile::UpdateUserTradeProfileRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::usertradeprofile::UpdateUserTradeProfileRequest, _impl_.user_account_id_),
        PROTOBUF_FIELD_OFFSET(::usertradeprofile::UpdateUserTradeProfileRequest, _impl_.leverage_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::usertradeprofile::UpdateUserTradeProfileResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::usertradeprofile::UpdateUserTradeProfileResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::usertradeprofile::UpdateUserTradeProfileResponse, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::usertradeprofile::UpdateUserTradeProfileRequest)},
        {10, -1, -1, sizeof(::usertradeprofile::UpdateUserTradeProfileResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::usertradeprofile::_UpdateUserTradeProfileRequest_default_instance_._instance,
    &::usertradeprofile::_UpdateUserTradeProfileResponse_default_instance_._instance,
};
const char descriptor_table_protodef_user_5ftrade_5fprofile_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030user_trade_profile.proto\022\020usertradepro"
    "file\"J\n\035UpdateUserTradeProfileRequest\022\027\n"
    "\017user_account_id\030\001 \001(\t\022\020\n\010leverage\030\002 \001(\001"
    "\"B\n\036UpdateUserTradeProfileResponse\022\017\n\007su"
    "ccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\213\001\n\014TradeSe"
    "rvice\022{\n\026UpdateUserTradeProfile\022/.usertr"
    "adeprofile.UpdateUserTradeProfileRequest"
    "\0320.usertradeprofile.UpdateUserTradeProfi"
    "leResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_user_5ftrade_5fprofile_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_user_5ftrade_5fprofile_2eproto = {
    false,
    false,
    338,
    descriptor_table_protodef_user_5ftrade_5fprofile_2eproto,
    "user_trade_profile.proto",
    &descriptor_table_user_5ftrade_5fprofile_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_user_5ftrade_5fprofile_2eproto::offsets,
    file_level_enum_descriptors_user_5ftrade_5fprofile_2eproto,
    file_level_service_descriptors_user_5ftrade_5fprofile_2eproto,
};
namespace usertradeprofile {
// ===================================================================

class UpdateUserTradeProfileRequest::_Internal {
 public:
};

UpdateUserTradeProfileRequest::UpdateUserTradeProfileRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:usertradeprofile.UpdateUserTradeProfileRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateUserTradeProfileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::usertradeprofile::UpdateUserTradeProfileRequest& from_msg)
      : user_account_id_(arena, from.user_account_id_),
        _cached_size_{0} {}

UpdateUserTradeProfileRequest::UpdateUserTradeProfileRequest(
    ::google::protobuf::Arena* arena,
    const UpdateUserTradeProfileRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateUserTradeProfileRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.leverage_ = from._impl_.leverage_;

  // @@protoc_insertion_point(copy_constructor:usertradeprofile.UpdateUserTradeProfileRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateUserTradeProfileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_account_id_(arena),
        _cached_size_{0} {}

inline void UpdateUserTradeProfileRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.leverage_ = {};
}
UpdateUserTradeProfileRequest::~UpdateUserTradeProfileRequest() {
  // @@protoc_insertion_point(destructor:usertradeprofile.UpdateUserTradeProfileRequest)
  SharedDtor(*this);
}
inline void UpdateUserTradeProfileRequest::SharedDtor(MessageLite& self) {
  UpdateUserTradeProfileRequest& this_ = static_cast<UpdateUserTradeProfileRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_account_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UpdateUserTradeProfileRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateUserTradeProfileRequest(arena);
}
constexpr auto UpdateUserTradeProfileRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UpdateUserTradeProfileRequest),
                                            alignof(UpdateUserTradeProfileRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateUserTradeProfileRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateUserTradeProfileRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateUserTradeProfileRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateUserTradeProfileRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateUserTradeProfileRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateUserTradeProfileRequest>(), &UpdateUserTradeProfileRequest::ByteSizeLong,
            &UpdateUserTradeProfileRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileRequest, _impl_._cached_size_),
        false,
    },
    &UpdateUserTradeProfileRequest::kDescriptorMethods,
    &descriptor_table_user_5ftrade_5fprofile_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateUserTradeProfileRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 70, 2> UpdateUserTradeProfileRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::usertradeprofile::UpdateUserTradeProfileRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double leverage = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileRequest, _impl_.leverage_)}},
    // string user_account_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileRequest, _impl_.user_account_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_account_id = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileRequest, _impl_.user_account_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double leverage = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileRequest, _impl_.leverage_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\56\17\0\0\0\0\0\0"
    "usertradeprofile.UpdateUserTradeProfileRequest"
    "user_account_id"
  }},
};

PROTOBUF_NOINLINE void UpdateUserTradeProfileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:usertradeprofile.UpdateUserTradeProfileRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_account_id_.ClearToEmpty();
  _impl_.leverage_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateUserTradeProfileRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateUserTradeProfileRequest& this_ = static_cast<const UpdateUserTradeProfileRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateUserTradeProfileRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateUserTradeProfileRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:usertradeprofile.UpdateUserTradeProfileRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string user_account_id = 1;
          if (!this_._internal_user_account_id().empty()) {
            const std::string& _s = this_._internal_user_account_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usertradeprofile.UpdateUserTradeProfileRequest.user_account_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double leverage = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_leverage()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_leverage(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:usertradeprofile.UpdateUserTradeProfileRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateUserTradeProfileRequest::ByteSizeLong(const MessageLite& base) {
          const UpdateUserTradeProfileRequest& this_ = static_cast<const UpdateUserTradeProfileRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateUserTradeProfileRequest::ByteSizeLong() const {
          const UpdateUserTradeProfileRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:usertradeprofile.UpdateUserTradeProfileRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string user_account_id = 1;
            if (!this_._internal_user_account_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_account_id());
            }
            // double leverage = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_leverage()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateUserTradeProfileRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateUserTradeProfileRequest*>(&to_msg);
  auto& from = static_cast<const UpdateUserTradeProfileRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:usertradeprofile.UpdateUserTradeProfileRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_account_id().empty()) {
    _this->_internal_set_user_account_id(from._internal_user_account_id());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_leverage()) != 0) {
    _this->_impl_.leverage_ = from._impl_.leverage_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateUserTradeProfileRequest::CopyFrom(const UpdateUserTradeProfileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:usertradeprofile.UpdateUserTradeProfileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateUserTradeProfileRequest::InternalSwap(UpdateUserTradeProfileRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_account_id_, &other->_impl_.user_account_id_, arena);
        swap(_impl_.leverage_, other->_impl_.leverage_);
}

::google::protobuf::Metadata UpdateUserTradeProfileRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateUserTradeProfileResponse::_Internal {
 public:
};

UpdateUserTradeProfileResponse::UpdateUserTradeProfileResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:usertradeprofile.UpdateUserTradeProfileResponse)
}
inline PROTOBUF_NDEBUG_INLINE UpdateUserTradeProfileResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::usertradeprofile::UpdateUserTradeProfileResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UpdateUserTradeProfileResponse::UpdateUserTradeProfileResponse(
    ::google::protobuf::Arena* arena,
    const UpdateUserTradeProfileResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateUserTradeProfileResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:usertradeprofile.UpdateUserTradeProfileResponse)
}
inline PROTOBUF_NDEBUG_INLINE UpdateUserTradeProfileResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UpdateUserTradeProfileResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
UpdateUserTradeProfileResponse::~UpdateUserTradeProfileResponse() {
  // @@protoc_insertion_point(destructor:usertradeprofile.UpdateUserTradeProfileResponse)
  SharedDtor(*this);
}
inline void UpdateUserTradeProfileResponse::SharedDtor(MessageLite& self) {
  UpdateUserTradeProfileResponse& this_ = static_cast<UpdateUserTradeProfileResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UpdateUserTradeProfileResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateUserTradeProfileResponse(arena);
}
constexpr auto UpdateUserTradeProfileResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UpdateUserTradeProfileResponse),
                                            alignof(UpdateUserTradeProfileResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateUserTradeProfileResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateUserTradeProfileResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateUserTradeProfileResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateUserTradeProfileResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateUserTradeProfileResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateUserTradeProfileResponse>(), &UpdateUserTradeProfileResponse::ByteSizeLong,
            &UpdateUserTradeProfileResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileResponse, _impl_._cached_size_),
        false,
    },
    &UpdateUserTradeProfileResponse::kDescriptorMethods,
    &descriptor_table_user_5ftrade_5fprofile_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateUserTradeProfileResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 63, 2> UpdateUserTradeProfileResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::usertradeprofile::UpdateUserTradeProfileResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileResponse, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateUserTradeProfileResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateUserTradeProfileResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\57\0\7\0\0\0\0\0"
    "usertradeprofile.UpdateUserTradeProfileResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void UpdateUserTradeProfileResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:usertradeprofile.UpdateUserTradeProfileResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateUserTradeProfileResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateUserTradeProfileResponse& this_ = static_cast<const UpdateUserTradeProfileResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateUserTradeProfileResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateUserTradeProfileResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:usertradeprofile.UpdateUserTradeProfileResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usertradeprofile.UpdateUserTradeProfileResponse.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:usertradeprofile.UpdateUserTradeProfileResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateUserTradeProfileResponse::ByteSizeLong(const MessageLite& base) {
          const UpdateUserTradeProfileResponse& this_ = static_cast<const UpdateUserTradeProfileResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateUserTradeProfileResponse::ByteSizeLong() const {
          const UpdateUserTradeProfileResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:usertradeprofile.UpdateUserTradeProfileResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateUserTradeProfileResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateUserTradeProfileResponse*>(&to_msg);
  auto& from = static_cast<const UpdateUserTradeProfileResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:usertradeprofile.UpdateUserTradeProfileResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateUserTradeProfileResponse::CopyFrom(const UpdateUserTradeProfileResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:usertradeprofile.UpdateUserTradeProfileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateUserTradeProfileResponse::InternalSwap(UpdateUserTradeProfileResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata UpdateUserTradeProfileResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace usertradeprofile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_user_5ftrade_5fprofile_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
