// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_trade_profile.proto
#ifndef GRPC_user_5ftrade_5fprofile_2eproto__INCLUDED
#define GRPC_user_5ftrade_5fprofile_2eproto__INCLUDED

#include "user_trade_profile.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace usertradeprofile {

// gRPC service definition
class TradeService final {
 public:
  static constexpr char const* service_full_name() {
    return "usertradeprofile.TradeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // RPC to update the user trade profile of a user account
    virtual ::grpc::Status UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::usertradeprofile::UpdateUserTradeProfileResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::usertradeprofile::UpdateUserTradeProfileResponse>> AsyncUpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::usertradeprofile::UpdateUserTradeProfileResponse>>(AsyncUpdateUserTradeProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::usertradeprofile::UpdateUserTradeProfileResponse>> PrepareAsyncUpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::usertradeprofile::UpdateUserTradeProfileResponse>>(PrepareAsyncUpdateUserTradeProfileRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // RPC to update the user trade profile of a user account
      virtual void UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::usertradeprofile::UpdateUserTradeProfileResponse>* AsyncUpdateUserTradeProfileRaw(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::usertradeprofile::UpdateUserTradeProfileResponse>* PrepareAsyncUpdateUserTradeProfileRaw(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::usertradeprofile::UpdateUserTradeProfileResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>> AsyncUpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>>(AsyncUpdateUserTradeProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>> PrepareAsyncUpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>>(PrepareAsyncUpdateUserTradeProfileRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateUserTradeProfile(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>* AsyncUpdateUserTradeProfileRaw(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::usertradeprofile::UpdateUserTradeProfileResponse>* PrepareAsyncUpdateUserTradeProfileRaw(::grpc::ClientContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateUserTradeProfile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // RPC to update the user trade profile of a user account
    virtual ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateUserTradeProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateUserTradeProfile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateUserTradeProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateUserTradeProfile(::grpc::ServerContext* context, ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::grpc::ServerAsyncResponseWriter< ::usertradeprofile::UpdateUserTradeProfileResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateUserTradeProfile<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UpdateUserTradeProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateUserTradeProfile() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::usertradeprofile::UpdateUserTradeProfileRequest* request, ::usertradeprofile::UpdateUserTradeProfileResponse* response) { return this->UpdateUserTradeProfile(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateUserTradeProfile(
        ::grpc::MessageAllocator< ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateUserTradeProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateUserTradeProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UpdateUserTradeProfile<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateUserTradeProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateUserTradeProfile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateUserTradeProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateUserTradeProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateUserTradeProfile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateUserTradeProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateUserTradeProfile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateUserTradeProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateUserTradeProfile() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateUserTradeProfile(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateUserTradeProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateUserTradeProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateUserTradeProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateUserTradeProfile() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::usertradeprofile::UpdateUserTradeProfileRequest, ::usertradeprofile::UpdateUserTradeProfileResponse>* streamer) {
                       return this->StreamedUpdateUserTradeProfile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateUserTradeProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateUserTradeProfile(::grpc::ServerContext* /*context*/, const ::usertradeprofile::UpdateUserTradeProfileRequest* /*request*/, ::usertradeprofile::UpdateUserTradeProfileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateUserTradeProfile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::usertradeprofile::UpdateUserTradeProfileRequest,::usertradeprofile::UpdateUserTradeProfileResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateUserTradeProfile<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateUserTradeProfile<Service > StreamedService;
};

}  // namespace usertradeprofile


#endif  // GRPC_user_5ftrade_5fprofile_2eproto__INCLUDED
