// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_trade_profile.proto
// Protobuf C++ Version: 5.29.2

#ifndef user_5ftrade_5fprofile_2eproto_2epb_2eh
#define user_5ftrade_5fprofile_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_user_5ftrade_5fprofile_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_user_5ftrade_5fprofile_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_user_5ftrade_5fprofile_2eproto;
namespace usertradeprofile {
class UpdateUserTradeProfileRequest;
struct UpdateUserTradeProfileRequestDefaultTypeInternal;
extern UpdateUserTradeProfileRequestDefaultTypeInternal _UpdateUserTradeProfileRequest_default_instance_;
class UpdateUserTradeProfileResponse;
struct UpdateUserTradeProfileResponseDefaultTypeInternal;
extern UpdateUserTradeProfileResponseDefaultTypeInternal _UpdateUserTradeProfileResponse_default_instance_;
}  // namespace usertradeprofile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace usertradeprofile {

// ===================================================================


// -------------------------------------------------------------------

class UpdateUserTradeProfileResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:usertradeprofile.UpdateUserTradeProfileResponse) */ {
 public:
  inline UpdateUserTradeProfileResponse() : UpdateUserTradeProfileResponse(nullptr) {}
  ~UpdateUserTradeProfileResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UpdateUserTradeProfileResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UpdateUserTradeProfileResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateUserTradeProfileResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline UpdateUserTradeProfileResponse(const UpdateUserTradeProfileResponse& from) : UpdateUserTradeProfileResponse(nullptr, from) {}
  inline UpdateUserTradeProfileResponse(UpdateUserTradeProfileResponse&& from) noexcept
      : UpdateUserTradeProfileResponse(nullptr, std::move(from)) {}
  inline UpdateUserTradeProfileResponse& operator=(const UpdateUserTradeProfileResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateUserTradeProfileResponse& operator=(UpdateUserTradeProfileResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateUserTradeProfileResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateUserTradeProfileResponse* internal_default_instance() {
    return reinterpret_cast<const UpdateUserTradeProfileResponse*>(
        &_UpdateUserTradeProfileResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UpdateUserTradeProfileResponse& a, UpdateUserTradeProfileResponse& b) { a.Swap(&b); }
  inline void Swap(UpdateUserTradeProfileResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateUserTradeProfileResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateUserTradeProfileResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UpdateUserTradeProfileResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UpdateUserTradeProfileResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UpdateUserTradeProfileResponse& from) { UpdateUserTradeProfileResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UpdateUserTradeProfileResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "usertradeprofile.UpdateUserTradeProfileResponse"; }

 protected:
  explicit UpdateUserTradeProfileResponse(::google::protobuf::Arena* arena);
  UpdateUserTradeProfileResponse(::google::protobuf::Arena* arena, const UpdateUserTradeProfileResponse& from);
  UpdateUserTradeProfileResponse(::google::protobuf::Arena* arena, UpdateUserTradeProfileResponse&& from) noexcept
      : UpdateUserTradeProfileResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:usertradeprofile.UpdateUserTradeProfileResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      63, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UpdateUserTradeProfileResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    bool success_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5ftrade_5fprofile_2eproto;
};
// -------------------------------------------------------------------

class UpdateUserTradeProfileRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:usertradeprofile.UpdateUserTradeProfileRequest) */ {
 public:
  inline UpdateUserTradeProfileRequest() : UpdateUserTradeProfileRequest(nullptr) {}
  ~UpdateUserTradeProfileRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UpdateUserTradeProfileRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UpdateUserTradeProfileRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateUserTradeProfileRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline UpdateUserTradeProfileRequest(const UpdateUserTradeProfileRequest& from) : UpdateUserTradeProfileRequest(nullptr, from) {}
  inline UpdateUserTradeProfileRequest(UpdateUserTradeProfileRequest&& from) noexcept
      : UpdateUserTradeProfileRequest(nullptr, std::move(from)) {}
  inline UpdateUserTradeProfileRequest& operator=(const UpdateUserTradeProfileRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateUserTradeProfileRequest& operator=(UpdateUserTradeProfileRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateUserTradeProfileRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateUserTradeProfileRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateUserTradeProfileRequest*>(
        &_UpdateUserTradeProfileRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(UpdateUserTradeProfileRequest& a, UpdateUserTradeProfileRequest& b) { a.Swap(&b); }
  inline void Swap(UpdateUserTradeProfileRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateUserTradeProfileRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateUserTradeProfileRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UpdateUserTradeProfileRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UpdateUserTradeProfileRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UpdateUserTradeProfileRequest& from) { UpdateUserTradeProfileRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UpdateUserTradeProfileRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "usertradeprofile.UpdateUserTradeProfileRequest"; }

 protected:
  explicit UpdateUserTradeProfileRequest(::google::protobuf::Arena* arena);
  UpdateUserTradeProfileRequest(::google::protobuf::Arena* arena, const UpdateUserTradeProfileRequest& from);
  UpdateUserTradeProfileRequest(::google::protobuf::Arena* arena, UpdateUserTradeProfileRequest&& from) noexcept
      : UpdateUserTradeProfileRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserAccountIdFieldNumber = 1,
    kLeverageFieldNumber = 2,
  };
  // string user_account_id = 1;
  void clear_user_account_id() ;
  const std::string& user_account_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_user_account_id(Arg_&& arg, Args_... args);
  std::string* mutable_user_account_id();
  PROTOBUF_NODISCARD std::string* release_user_account_id();
  void set_allocated_user_account_id(std::string* value);

  private:
  const std::string& _internal_user_account_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_account_id(
      const std::string& value);
  std::string* _internal_mutable_user_account_id();

  public:
  // double leverage = 2;
  void clear_leverage() ;
  double leverage() const;
  void set_leverage(double value);

  private:
  double _internal_leverage() const;
  void _internal_set_leverage(double value);

  public:
  // @@protoc_insertion_point(class_scope:usertradeprofile.UpdateUserTradeProfileRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      70, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UpdateUserTradeProfileRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr user_account_id_;
    double leverage_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5ftrade_5fprofile_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UpdateUserTradeProfileRequest

// string user_account_id = 1;
inline void UpdateUserTradeProfileRequest::clear_user_account_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_account_id_.ClearToEmpty();
}
inline const std::string& UpdateUserTradeProfileRequest::user_account_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usertradeprofile.UpdateUserTradeProfileRequest.user_account_id)
  return _internal_user_account_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateUserTradeProfileRequest::set_user_account_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_account_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usertradeprofile.UpdateUserTradeProfileRequest.user_account_id)
}
inline std::string* UpdateUserTradeProfileRequest::mutable_user_account_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_user_account_id();
  // @@protoc_insertion_point(field_mutable:usertradeprofile.UpdateUserTradeProfileRequest.user_account_id)
  return _s;
}
inline const std::string& UpdateUserTradeProfileRequest::_internal_user_account_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_account_id_.Get();
}
inline void UpdateUserTradeProfileRequest::_internal_set_user_account_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_account_id_.Set(value, GetArena());
}
inline std::string* UpdateUserTradeProfileRequest::_internal_mutable_user_account_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_account_id_.Mutable( GetArena());
}
inline std::string* UpdateUserTradeProfileRequest::release_user_account_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usertradeprofile.UpdateUserTradeProfileRequest.user_account_id)
  return _impl_.user_account_id_.Release();
}
inline void UpdateUserTradeProfileRequest::set_allocated_user_account_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_account_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_account_id_.IsDefault()) {
    _impl_.user_account_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usertradeprofile.UpdateUserTradeProfileRequest.user_account_id)
}

// double leverage = 2;
inline void UpdateUserTradeProfileRequest::clear_leverage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leverage_ = 0;
}
inline double UpdateUserTradeProfileRequest::leverage() const {
  // @@protoc_insertion_point(field_get:usertradeprofile.UpdateUserTradeProfileRequest.leverage)
  return _internal_leverage();
}
inline void UpdateUserTradeProfileRequest::set_leverage(double value) {
  _internal_set_leverage(value);
  // @@protoc_insertion_point(field_set:usertradeprofile.UpdateUserTradeProfileRequest.leverage)
}
inline double UpdateUserTradeProfileRequest::_internal_leverage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leverage_;
}
inline void UpdateUserTradeProfileRequest::_internal_set_leverage(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leverage_ = value;
}

// -------------------------------------------------------------------

// UpdateUserTradeProfileResponse

// bool success = 1;
inline void UpdateUserTradeProfileResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool UpdateUserTradeProfileResponse::success() const {
  // @@protoc_insertion_point(field_get:usertradeprofile.UpdateUserTradeProfileResponse.success)
  return _internal_success();
}
inline void UpdateUserTradeProfileResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:usertradeprofile.UpdateUserTradeProfileResponse.success)
}
inline bool UpdateUserTradeProfileResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void UpdateUserTradeProfileResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string message = 2;
inline void UpdateUserTradeProfileResponse::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& UpdateUserTradeProfileResponse::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usertradeprofile.UpdateUserTradeProfileResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateUserTradeProfileResponse::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usertradeprofile.UpdateUserTradeProfileResponse.message)
}
inline std::string* UpdateUserTradeProfileResponse::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:usertradeprofile.UpdateUserTradeProfileResponse.message)
  return _s;
}
inline const std::string& UpdateUserTradeProfileResponse::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void UpdateUserTradeProfileResponse::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* UpdateUserTradeProfileResponse::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* UpdateUserTradeProfileResponse::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usertradeprofile.UpdateUserTradeProfileResponse.message)
  return _impl_.message_.Release();
}
inline void UpdateUserTradeProfileResponse::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usertradeprofile.UpdateUserTradeProfileResponse.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace usertradeprofile


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // user_5ftrade_5fprofile_2eproto_2epb_2eh
