// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_account_data.proto
// Protobuf C++ Version: 5.29.2

#ifndef user_5faccount_5fdata_2eproto_2epb_2eh
#define user_5faccount_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_user_5faccount_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_user_5faccount_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_user_5faccount_5fdata_2eproto;
namespace account {
class Balance;
struct BalanceDefaultTypeInternal;
extern BalanceDefaultTypeInternal _Balance_default_instance_;
class UserAccountDataRequest;
struct UserAccountDataRequestDefaultTypeInternal;
extern UserAccountDataRequestDefaultTypeInternal _UserAccountDataRequest_default_instance_;
class UserAccountDataResponse;
struct UserAccountDataResponseDefaultTypeInternal;
extern UserAccountDataResponseDefaultTypeInternal _UserAccountDataResponse_default_instance_;
class UserAccountDataResponse_BalancesEntry_DoNotUse;
struct UserAccountDataResponse_BalancesEntry_DoNotUseDefaultTypeInternal;
extern UserAccountDataResponse_BalancesEntry_DoNotUseDefaultTypeInternal _UserAccountDataResponse_BalancesEntry_DoNotUse_default_instance_;
}  // namespace account
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace account {

// ===================================================================


// -------------------------------------------------------------------

class UserAccountDataRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:account.UserAccountDataRequest) */ {
 public:
  inline UserAccountDataRequest() : UserAccountDataRequest(nullptr) {}
  ~UserAccountDataRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UserAccountDataRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UserAccountDataRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserAccountDataRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline UserAccountDataRequest(const UserAccountDataRequest& from) : UserAccountDataRequest(nullptr, from) {}
  inline UserAccountDataRequest(UserAccountDataRequest&& from) noexcept
      : UserAccountDataRequest(nullptr, std::move(from)) {}
  inline UserAccountDataRequest& operator=(const UserAccountDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserAccountDataRequest& operator=(UserAccountDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserAccountDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserAccountDataRequest* internal_default_instance() {
    return reinterpret_cast<const UserAccountDataRequest*>(
        &_UserAccountDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UserAccountDataRequest& a, UserAccountDataRequest& b) { a.Swap(&b); }
  inline void Swap(UserAccountDataRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserAccountDataRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserAccountDataRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UserAccountDataRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UserAccountDataRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UserAccountDataRequest& from) { UserAccountDataRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UserAccountDataRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "account.UserAccountDataRequest"; }

 protected:
  explicit UserAccountDataRequest(::google::protobuf::Arena* arena);
  UserAccountDataRequest(::google::protobuf::Arena* arena, const UserAccountDataRequest& from);
  UserAccountDataRequest(::google::protobuf::Arena* arena, UserAccountDataRequest&& from) noexcept
      : UserAccountDataRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
  };
  // string user_id = 1;
  void clear_user_id() ;
  const std::string& user_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_user_id(Arg_&& arg, Args_... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* value);

  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(
      const std::string& value);
  std::string* _internal_mutable_user_id();

  public:
  // @@protoc_insertion_point(class_scope:account.UserAccountDataRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      46, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UserAccountDataRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr user_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5faccount_5fdata_2eproto;
};
// -------------------------------------------------------------------

class Balance final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:account.Balance) */ {
 public:
  inline Balance() : Balance(nullptr) {}
  ~Balance() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Balance* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Balance));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Balance(
      ::google::protobuf::internal::ConstantInitialized);

  inline Balance(const Balance& from) : Balance(nullptr, from) {}
  inline Balance(Balance&& from) noexcept
      : Balance(nullptr, std::move(from)) {}
  inline Balance& operator=(const Balance& from) {
    CopyFrom(from);
    return *this;
  }
  inline Balance& operator=(Balance&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Balance& default_instance() {
    return *internal_default_instance();
  }
  static inline const Balance* internal_default_instance() {
    return reinterpret_cast<const Balance*>(
        &_Balance_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Balance& a, Balance& b) { a.Swap(&b); }
  inline void Swap(Balance* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Balance* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Balance* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Balance>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Balance& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Balance& from) { Balance::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Balance* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "account.Balance"; }

 protected:
  explicit Balance(::google::protobuf::Arena* arena);
  Balance(::google::protobuf::Arena* arena, const Balance& from);
  Balance(::google::protobuf::Arena* arena, Balance&& from) noexcept
      : Balance(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAssetSymbolFieldNumber = 1,
    kFreeAmountFieldNumber = 2,
    kLockedAmountFieldNumber = 3,
  };
  // string asset_symbol = 1;
  void clear_asset_symbol() ;
  const std::string& asset_symbol() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_asset_symbol();
  PROTOBUF_NODISCARD std::string* release_asset_symbol();
  void set_allocated_asset_symbol(std::string* value);

  private:
  const std::string& _internal_asset_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset_symbol(
      const std::string& value);
  std::string* _internal_mutable_asset_symbol();

  public:
  // double free_amount = 2;
  void clear_free_amount() ;
  double free_amount() const;
  void set_free_amount(double value);

  private:
  double _internal_free_amount() const;
  void _internal_set_free_amount(double value);

  public:
  // double locked_amount = 3;
  void clear_locked_amount() ;
  double locked_amount() const;
  void set_locked_amount(double value);

  private:
  double _internal_locked_amount() const;
  void _internal_set_locked_amount(double value);

  public:
  // @@protoc_insertion_point(class_scope:account.Balance)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      36, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Balance& from_msg);
    ::google::protobuf::internal::ArenaStringPtr asset_symbol_;
    double free_amount_;
    double locked_amount_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5faccount_5fdata_2eproto;
};
// -------------------------------------------------------------------

class UserAccountDataResponse_BalancesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, ::google::protobuf::Message,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, ::google::protobuf::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  UserAccountDataResponse_BalancesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserAccountDataResponse_BalancesEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit UserAccountDataResponse_BalancesEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const UserAccountDataResponse_BalancesEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const UserAccountDataResponse_BalancesEntry_DoNotUse*>(
        &_UserAccountDataResponse_BalancesEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_user_5faccount_5fdata_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      57, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class UserAccountDataResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:account.UserAccountDataResponse) */ {
 public:
  inline UserAccountDataResponse() : UserAccountDataResponse(nullptr) {}
  ~UserAccountDataResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UserAccountDataResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UserAccountDataResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserAccountDataResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline UserAccountDataResponse(const UserAccountDataResponse& from) : UserAccountDataResponse(nullptr, from) {}
  inline UserAccountDataResponse(UserAccountDataResponse&& from) noexcept
      : UserAccountDataResponse(nullptr, std::move(from)) {}
  inline UserAccountDataResponse& operator=(const UserAccountDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserAccountDataResponse& operator=(UserAccountDataResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserAccountDataResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserAccountDataResponse* internal_default_instance() {
    return reinterpret_cast<const UserAccountDataResponse*>(
        &_UserAccountDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(UserAccountDataResponse& a, UserAccountDataResponse& b) { a.Swap(&b); }
  inline void Swap(UserAccountDataResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserAccountDataResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserAccountDataResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UserAccountDataResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UserAccountDataResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UserAccountDataResponse& from) { UserAccountDataResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UserAccountDataResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "account.UserAccountDataResponse"; }

 protected:
  explicit UserAccountDataResponse(::google::protobuf::Arena* arena);
  UserAccountDataResponse(::google::protobuf::Arena* arena, const UserAccountDataResponse& from);
  UserAccountDataResponse(::google::protobuf::Arena* arena, UserAccountDataResponse&& from) noexcept
      : UserAccountDataResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBalancesFieldNumber = 11,
    kUserIdFieldNumber = 1,
    kMakerCommissionFieldNumber = 2,
    kTakerCommissionFieldNumber = 3,
    kBuyerCommissionFieldNumber = 4,
    kSellerCommissionFieldNumber = 5,
    kUpdateTimeFieldNumber = 6,
    kStableCoinAmountFieldNumber = 10,
    kCanTradeFieldNumber = 7,
    kCanWithdrawFieldNumber = 8,
    kCanDepositFieldNumber = 9,
  };
  // map<string, .account.Balance> balances = 11;
  int balances_size() const;
  private:
  int _internal_balances_size() const;

  public:
  void clear_balances() ;
  const ::google::protobuf::Map<std::string, ::account::Balance>& balances() const;
  ::google::protobuf::Map<std::string, ::account::Balance>* mutable_balances();

  private:
  const ::google::protobuf::Map<std::string, ::account::Balance>& _internal_balances() const;
  ::google::protobuf::Map<std::string, ::account::Balance>* _internal_mutable_balances();

  public:
  // string user_id = 1;
  void clear_user_id() ;
  const std::string& user_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_user_id(Arg_&& arg, Args_... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* value);

  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(
      const std::string& value);
  std::string* _internal_mutable_user_id();

  public:
  // uint32 maker_commission = 2;
  void clear_maker_commission() ;
  ::uint32_t maker_commission() const;
  void set_maker_commission(::uint32_t value);

  private:
  ::uint32_t _internal_maker_commission() const;
  void _internal_set_maker_commission(::uint32_t value);

  public:
  // uint32 taker_commission = 3;
  void clear_taker_commission() ;
  ::uint32_t taker_commission() const;
  void set_taker_commission(::uint32_t value);

  private:
  ::uint32_t _internal_taker_commission() const;
  void _internal_set_taker_commission(::uint32_t value);

  public:
  // uint32 buyer_commission = 4;
  void clear_buyer_commission() ;
  ::uint32_t buyer_commission() const;
  void set_buyer_commission(::uint32_t value);

  private:
  ::uint32_t _internal_buyer_commission() const;
  void _internal_set_buyer_commission(::uint32_t value);

  public:
  // uint32 seller_commission = 5;
  void clear_seller_commission() ;
  ::uint32_t seller_commission() const;
  void set_seller_commission(::uint32_t value);

  private:
  ::uint32_t _internal_seller_commission() const;
  void _internal_set_seller_commission(::uint32_t value);

  public:
  // uint64 update_time = 6;
  void clear_update_time() ;
  ::uint64_t update_time() const;
  void set_update_time(::uint64_t value);

  private:
  ::uint64_t _internal_update_time() const;
  void _internal_set_update_time(::uint64_t value);

  public:
  // double stable_coin_amount = 10;
  void clear_stable_coin_amount() ;
  double stable_coin_amount() const;
  void set_stable_coin_amount(double value);

  private:
  double _internal_stable_coin_amount() const;
  void _internal_set_stable_coin_amount(double value);

  public:
  // bool can_trade = 7;
  void clear_can_trade() ;
  bool can_trade() const;
  void set_can_trade(bool value);

  private:
  bool _internal_can_trade() const;
  void _internal_set_can_trade(bool value);

  public:
  // bool can_withdraw = 8;
  void clear_can_withdraw() ;
  bool can_withdraw() const;
  void set_can_withdraw(bool value);

  private:
  bool _internal_can_withdraw() const;
  void _internal_set_can_withdraw(bool value);

  public:
  // bool can_deposit = 9;
  void clear_can_deposit() ;
  bool can_deposit() const;
  void set_can_deposit(bool value);

  private:
  bool _internal_can_deposit() const;
  void _internal_set_can_deposit(bool value);

  public:
  // @@protoc_insertion_point(class_scope:account.UserAccountDataResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 11, 2,
      63, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UserAccountDataResponse& from_msg);
    ::google::protobuf::internal::MapField<UserAccountDataResponse_BalancesEntry_DoNotUse, std::string, ::account::Balance,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        balances_;
    ::google::protobuf::internal::ArenaStringPtr user_id_;
    ::uint32_t maker_commission_;
    ::uint32_t taker_commission_;
    ::uint32_t buyer_commission_;
    ::uint32_t seller_commission_;
    ::uint64_t update_time_;
    double stable_coin_amount_;
    bool can_trade_;
    bool can_withdraw_;
    bool can_deposit_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5faccount_5fdata_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Balance

// string asset_symbol = 1;
inline void Balance::clear_asset_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset_symbol_.ClearToEmpty();
}
inline const std::string& Balance::asset_symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account.Balance.asset_symbol)
  return _internal_asset_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Balance::set_asset_symbol(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset_symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:account.Balance.asset_symbol)
}
inline std::string* Balance::mutable_asset_symbol() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset_symbol();
  // @@protoc_insertion_point(field_mutable:account.Balance.asset_symbol)
  return _s;
}
inline const std::string& Balance::_internal_asset_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.asset_symbol_.Get();
}
inline void Balance::_internal_set_asset_symbol(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset_symbol_.Set(value, GetArena());
}
inline std::string* Balance::_internal_mutable_asset_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.asset_symbol_.Mutable( GetArena());
}
inline std::string* Balance::release_asset_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:account.Balance.asset_symbol)
  return _impl_.asset_symbol_.Release();
}
inline void Balance::set_allocated_asset_symbol(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset_symbol_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.asset_symbol_.IsDefault()) {
    _impl_.asset_symbol_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:account.Balance.asset_symbol)
}

// double free_amount = 2;
inline void Balance::clear_free_amount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.free_amount_ = 0;
}
inline double Balance::free_amount() const {
  // @@protoc_insertion_point(field_get:account.Balance.free_amount)
  return _internal_free_amount();
}
inline void Balance::set_free_amount(double value) {
  _internal_set_free_amount(value);
  // @@protoc_insertion_point(field_set:account.Balance.free_amount)
}
inline double Balance::_internal_free_amount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.free_amount_;
}
inline void Balance::_internal_set_free_amount(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.free_amount_ = value;
}

// double locked_amount = 3;
inline void Balance::clear_locked_amount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.locked_amount_ = 0;
}
inline double Balance::locked_amount() const {
  // @@protoc_insertion_point(field_get:account.Balance.locked_amount)
  return _internal_locked_amount();
}
inline void Balance::set_locked_amount(double value) {
  _internal_set_locked_amount(value);
  // @@protoc_insertion_point(field_set:account.Balance.locked_amount)
}
inline double Balance::_internal_locked_amount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.locked_amount_;
}
inline void Balance::_internal_set_locked_amount(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.locked_amount_ = value;
}

// -------------------------------------------------------------------

// UserAccountDataRequest

// string user_id = 1;
inline void UserAccountDataRequest::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& UserAccountDataRequest::user_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account.UserAccountDataRequest.user_id)
  return _internal_user_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserAccountDataRequest::set_user_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:account.UserAccountDataRequest.user_id)
}
inline std::string* UserAccountDataRequest::mutable_user_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:account.UserAccountDataRequest.user_id)
  return _s;
}
inline const std::string& UserAccountDataRequest::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_.Get();
}
inline void UserAccountDataRequest::_internal_set_user_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(value, GetArena());
}
inline std::string* UserAccountDataRequest::_internal_mutable_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_id_.Mutable( GetArena());
}
inline std::string* UserAccountDataRequest::release_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:account.UserAccountDataRequest.user_id)
  return _impl_.user_id_.Release();
}
inline void UserAccountDataRequest::set_allocated_user_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:account.UserAccountDataRequest.user_id)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// UserAccountDataResponse

// string user_id = 1;
inline void UserAccountDataResponse::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& UserAccountDataResponse::user_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.user_id)
  return _internal_user_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserAccountDataResponse::set_user_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.user_id)
}
inline std::string* UserAccountDataResponse::mutable_user_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:account.UserAccountDataResponse.user_id)
  return _s;
}
inline const std::string& UserAccountDataResponse::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_.Get();
}
inline void UserAccountDataResponse::_internal_set_user_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(value, GetArena());
}
inline std::string* UserAccountDataResponse::_internal_mutable_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_id_.Mutable( GetArena());
}
inline std::string* UserAccountDataResponse::release_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:account.UserAccountDataResponse.user_id)
  return _impl_.user_id_.Release();
}
inline void UserAccountDataResponse::set_allocated_user_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:account.UserAccountDataResponse.user_id)
}

// uint32 maker_commission = 2;
inline void UserAccountDataResponse::clear_maker_commission() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maker_commission_ = 0u;
}
inline ::uint32_t UserAccountDataResponse::maker_commission() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.maker_commission)
  return _internal_maker_commission();
}
inline void UserAccountDataResponse::set_maker_commission(::uint32_t value) {
  _internal_set_maker_commission(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.maker_commission)
}
inline ::uint32_t UserAccountDataResponse::_internal_maker_commission() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.maker_commission_;
}
inline void UserAccountDataResponse::_internal_set_maker_commission(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maker_commission_ = value;
}

// uint32 taker_commission = 3;
inline void UserAccountDataResponse::clear_taker_commission() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.taker_commission_ = 0u;
}
inline ::uint32_t UserAccountDataResponse::taker_commission() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.taker_commission)
  return _internal_taker_commission();
}
inline void UserAccountDataResponse::set_taker_commission(::uint32_t value) {
  _internal_set_taker_commission(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.taker_commission)
}
inline ::uint32_t UserAccountDataResponse::_internal_taker_commission() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.taker_commission_;
}
inline void UserAccountDataResponse::_internal_set_taker_commission(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.taker_commission_ = value;
}

// uint32 buyer_commission = 4;
inline void UserAccountDataResponse::clear_buyer_commission() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buyer_commission_ = 0u;
}
inline ::uint32_t UserAccountDataResponse::buyer_commission() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.buyer_commission)
  return _internal_buyer_commission();
}
inline void UserAccountDataResponse::set_buyer_commission(::uint32_t value) {
  _internal_set_buyer_commission(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.buyer_commission)
}
inline ::uint32_t UserAccountDataResponse::_internal_buyer_commission() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.buyer_commission_;
}
inline void UserAccountDataResponse::_internal_set_buyer_commission(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buyer_commission_ = value;
}

// uint32 seller_commission = 5;
inline void UserAccountDataResponse::clear_seller_commission() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seller_commission_ = 0u;
}
inline ::uint32_t UserAccountDataResponse::seller_commission() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.seller_commission)
  return _internal_seller_commission();
}
inline void UserAccountDataResponse::set_seller_commission(::uint32_t value) {
  _internal_set_seller_commission(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.seller_commission)
}
inline ::uint32_t UserAccountDataResponse::_internal_seller_commission() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seller_commission_;
}
inline void UserAccountDataResponse::_internal_set_seller_commission(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seller_commission_ = value;
}

// uint64 update_time = 6;
inline void UserAccountDataResponse::clear_update_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = ::uint64_t{0u};
}
inline ::uint64_t UserAccountDataResponse::update_time() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.update_time)
  return _internal_update_time();
}
inline void UserAccountDataResponse::set_update_time(::uint64_t value) {
  _internal_set_update_time(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.update_time)
}
inline ::uint64_t UserAccountDataResponse::_internal_update_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.update_time_;
}
inline void UserAccountDataResponse::_internal_set_update_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = value;
}

// bool can_trade = 7;
inline void UserAccountDataResponse::clear_can_trade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.can_trade_ = false;
}
inline bool UserAccountDataResponse::can_trade() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.can_trade)
  return _internal_can_trade();
}
inline void UserAccountDataResponse::set_can_trade(bool value) {
  _internal_set_can_trade(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.can_trade)
}
inline bool UserAccountDataResponse::_internal_can_trade() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.can_trade_;
}
inline void UserAccountDataResponse::_internal_set_can_trade(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.can_trade_ = value;
}

// bool can_withdraw = 8;
inline void UserAccountDataResponse::clear_can_withdraw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.can_withdraw_ = false;
}
inline bool UserAccountDataResponse::can_withdraw() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.can_withdraw)
  return _internal_can_withdraw();
}
inline void UserAccountDataResponse::set_can_withdraw(bool value) {
  _internal_set_can_withdraw(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.can_withdraw)
}
inline bool UserAccountDataResponse::_internal_can_withdraw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.can_withdraw_;
}
inline void UserAccountDataResponse::_internal_set_can_withdraw(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.can_withdraw_ = value;
}

// bool can_deposit = 9;
inline void UserAccountDataResponse::clear_can_deposit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.can_deposit_ = false;
}
inline bool UserAccountDataResponse::can_deposit() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.can_deposit)
  return _internal_can_deposit();
}
inline void UserAccountDataResponse::set_can_deposit(bool value) {
  _internal_set_can_deposit(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.can_deposit)
}
inline bool UserAccountDataResponse::_internal_can_deposit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.can_deposit_;
}
inline void UserAccountDataResponse::_internal_set_can_deposit(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.can_deposit_ = value;
}

// double stable_coin_amount = 10;
inline void UserAccountDataResponse::clear_stable_coin_amount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stable_coin_amount_ = 0;
}
inline double UserAccountDataResponse::stable_coin_amount() const {
  // @@protoc_insertion_point(field_get:account.UserAccountDataResponse.stable_coin_amount)
  return _internal_stable_coin_amount();
}
inline void UserAccountDataResponse::set_stable_coin_amount(double value) {
  _internal_set_stable_coin_amount(value);
  // @@protoc_insertion_point(field_set:account.UserAccountDataResponse.stable_coin_amount)
}
inline double UserAccountDataResponse::_internal_stable_coin_amount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stable_coin_amount_;
}
inline void UserAccountDataResponse::_internal_set_stable_coin_amount(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stable_coin_amount_ = value;
}

// map<string, .account.Balance> balances = 11;
inline int UserAccountDataResponse::_internal_balances_size() const {
  return _internal_balances().size();
}
inline int UserAccountDataResponse::balances_size() const {
  return _internal_balances_size();
}
inline void UserAccountDataResponse::clear_balances() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.balances_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::account::Balance>& UserAccountDataResponse::_internal_balances() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.balances_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::account::Balance>& UserAccountDataResponse::balances() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:account.UserAccountDataResponse.balances)
  return _internal_balances();
}
inline ::google::protobuf::Map<std::string, ::account::Balance>* UserAccountDataResponse::_internal_mutable_balances() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.balances_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::account::Balance>* UserAccountDataResponse::mutable_balances() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:account.UserAccountDataResponse.balances)
  return _internal_mutable_balances();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace account


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // user_5faccount_5fdata_2eproto_2epb_2eh
