/*#*******************************************************************************
# COPYRIGHT NOTES
# ---------------
# This is a part of Binance Quant Trader Project
# Copyright(C) - vinadevs
# This source code can be used, distributed or modified under Apache license
#*******************************************************************************/ 

// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_account_data.proto
// Original file comments:
// user_account_data.proto
#ifndef GRPC_user_5faccount_5fdata_2eproto__INCLUDED
#define GRPC_user_5faccount_5fdata_2eproto__INCLUDED

#include "user_account_data.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class UserAccountService final {
 public:
  static constexpr char const* service_full_name() {
    return "UserAccountService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::UserAccountDataResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserAccountDataResponse>> AsyncGetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserAccountDataResponse>>(AsyncGetUserAccountDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserAccountDataResponse>> PrepareAsyncGetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserAccountDataResponse>>(PrepareAsyncGetUserAccountDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest* request, ::UserAccountDataResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest* request, ::UserAccountDataResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UserAccountDataResponse>* AsyncGetUserAccountDataRaw(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UserAccountDataResponse>* PrepareAsyncGetUserAccountDataRaw(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::UserAccountDataResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserAccountDataResponse>> AsyncGetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserAccountDataResponse>>(AsyncGetUserAccountDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserAccountDataResponse>> PrepareAsyncGetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserAccountDataResponse>>(PrepareAsyncGetUserAccountDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest* request, ::UserAccountDataResponse* response, std::function<void(::grpc::Status)>) override;
      void GetUserAccountData(::grpc::ClientContext* context, const ::UserAccountDataRequest* request, ::UserAccountDataResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::UserAccountDataResponse>* AsyncGetUserAccountDataRaw(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UserAccountDataResponse>* PrepareAsyncGetUserAccountDataRaw(::grpc::ClientContext* context, const ::UserAccountDataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUserAccountData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetUserAccountData(::grpc::ServerContext* context, const ::UserAccountDataRequest* request, ::UserAccountDataResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserAccountData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUserAccountData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUserAccountData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserAccountData(::grpc::ServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserAccountData(::grpc::ServerContext* context, ::UserAccountDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::UserAccountDataResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUserAccountData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUserAccountData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUserAccountData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::UserAccountDataRequest, ::UserAccountDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::UserAccountDataRequest* request, ::UserAccountDataResponse* response) { return this->GetUserAccountData(context, request, response); }));}
    void SetMessageAllocatorFor_GetUserAccountData(
        ::grpc::MessageAllocator< ::UserAccountDataRequest, ::UserAccountDataResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::UserAccountDataRequest, ::UserAccountDataResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUserAccountData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserAccountData(::grpc::ServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserAccountData(
      ::grpc::CallbackServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUserAccountData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUserAccountData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUserAccountData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUserAccountData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserAccountData(::grpc::ServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUserAccountData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUserAccountData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUserAccountData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserAccountData(::grpc::ServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserAccountData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUserAccountData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUserAccountData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUserAccountData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUserAccountData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserAccountData(::grpc::ServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserAccountData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserAccountData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUserAccountData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::UserAccountDataRequest, ::UserAccountDataResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::UserAccountDataRequest, ::UserAccountDataResponse>* streamer) {
                       return this->StreamedGetUserAccountData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUserAccountData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserAccountData(::grpc::ServerContext* /*context*/, const ::UserAccountDataRequest* /*request*/, ::UserAccountDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserAccountData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::UserAccountDataRequest,::UserAccountDataResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUserAccountData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUserAccountData<Service > StreamedService;
};


#endif  // GRPC_user_5faccount_5fdata_2eproto__INCLUDED
