// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_future_account_data.proto

#include "pch.h"

#include "user_future_account_data.pb.h"
#include "user_future_account_data.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace futureaccount {

static const char* UserAccountService_method_names[] = {
  "/futureaccount.UserAccountService/GetUserFutureAccount",
};

std::unique_ptr< UserAccountService::Stub> UserAccountService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserAccountService::Stub> stub(new UserAccountService::Stub(channel, options));
  return stub;
}

UserAccountService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetUserFutureAccount_(UserAccountService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserAccountService::Stub::GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::futureaccount::GetUserFutureAccountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUserFutureAccount_, context, request, response);
}

void UserAccountService::Stub::async::GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserFutureAccount_, context, request, response, std::move(f));
}

void UserAccountService::Stub::async::GetUserFutureAccount(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserFutureAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>* UserAccountService::Stub::PrepareAsyncGetUserFutureAccountRaw(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::futureaccount::GetUserFutureAccountResponse, ::futureaccount::GetUserFutureAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUserFutureAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::futureaccount::GetUserFutureAccountResponse>* UserAccountService::Stub::AsyncGetUserFutureAccountRaw(::grpc::ClientContext* context, const ::futureaccount::GetUserFutureAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserFutureAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserAccountService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserAccountService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserAccountService::Service, ::futureaccount::GetUserFutureAccountRequest, ::futureaccount::GetUserFutureAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserAccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::futureaccount::GetUserFutureAccountRequest* req,
             ::futureaccount::GetUserFutureAccountResponse* resp) {
               return service->GetUserFutureAccount(ctx, req, resp);
             }, this)));
}

UserAccountService::Service::~Service() {
}

::grpc::Status UserAccountService::Service::GetUserFutureAccount(::grpc::ServerContext* context, const ::futureaccount::GetUserFutureAccountRequest* request, ::futureaccount::GetUserFutureAccountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace futureaccount

