syntax = "proto3";

package strategy;

// Status enum for order execution
enum OrderStatus {
    ORDER_SUCCESS = 0;
    ORDER_FAILED = 1;
}

// Parent order request
message StrategyParentOrderRequest {
    string symbol = 1;
    double price = 2;
    double quantity = 3;

    string strategy = 4;
    string start_time = 5;
    string end_time = 6;
    string side = 7;
    string child_order_type = 8;

    string parent_order_type = 9;   // NEW, CANCEL, AMEND
    string parent_order_id   = 10;  // ID of THIS order
    string original_parent_order_id = 11; // NEW FIELD: ID of the first/root order
}

// Response
message StrategyParentOrderResponse {
    OrderStatus status = 1;
    string error_message = 2;
}

// gRPC service
service StrategyOrderService {
    rpc SubmitParentOrder(StrategyParentOrderRequest)
        returns (StrategyParentOrderResponse);
}
