# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import strategy_parent_order_pb2 as strategy__parent__order__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in strategy_parent_order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyOrderServiceStub(object):
    """gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitParentOrder = channel.unary_unary(
                '/strategy.StrategyOrderService/SubmitParentOrder',
                request_serializer=strategy__parent__order__pb2.StrategyParentOrderRequest.SerializeToString,
                response_deserializer=strategy__parent__order__pb2.StrategyParentOrderResponse.FromString,
                _registered_method=True)


class StrategyOrderServiceServicer(object):
    """gRPC service
    """

    def SubmitParentOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitParentOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitParentOrder,
                    request_deserializer=strategy__parent__order__pb2.StrategyParentOrderRequest.FromString,
                    response_serializer=strategy__parent__order__pb2.StrategyParentOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strategy.StrategyOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('strategy.StrategyOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyOrderService(object):
    """gRPC service
    """

    @staticmethod
    def SubmitParentOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyOrderService/SubmitParentOrder',
            strategy__parent__order__pb2.StrategyParentOrderRequest.SerializeToString,
            strategy__parent__order__pb2.StrategyParentOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
