// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: strategy_parent_order.proto
// Protobuf C++ Version: 5.29.2

#ifndef strategy_5fparent_5forder_2eproto_2epb_2eh
#define strategy_5fparent_5forder_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_strategy_5fparent_5forder_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_strategy_5fparent_5forder_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_strategy_5fparent_5forder_2eproto;
namespace strategy {
class StrategyParentOrderRequest;
struct StrategyParentOrderRequestDefaultTypeInternal;
extern StrategyParentOrderRequestDefaultTypeInternal _StrategyParentOrderRequest_default_instance_;
class StrategyParentOrderResponse;
struct StrategyParentOrderResponseDefaultTypeInternal;
extern StrategyParentOrderResponseDefaultTypeInternal _StrategyParentOrderResponse_default_instance_;
}  // namespace strategy
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace strategy {
enum OrderStatus : int {
  ORDER_SUCCESS = 0,
  ORDER_FAILED = 1,
  OrderStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OrderStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OrderStatus_IsValid(int value);
extern const uint32_t OrderStatus_internal_data_[];
constexpr OrderStatus OrderStatus_MIN = static_cast<OrderStatus>(0);
constexpr OrderStatus OrderStatus_MAX = static_cast<OrderStatus>(1);
constexpr int OrderStatus_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
OrderStatus_descriptor();
template <typename T>
const std::string& OrderStatus_Name(T value) {
  static_assert(std::is_same<T, OrderStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OrderStatus_Name().");
  return OrderStatus_Name(static_cast<OrderStatus>(value));
}
template <>
inline const std::string& OrderStatus_Name(OrderStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OrderStatus_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool OrderStatus_Parse(absl::string_view name, OrderStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OrderStatus>(
      OrderStatus_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class StrategyParentOrderResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:strategy.StrategyParentOrderResponse) */ {
 public:
  inline StrategyParentOrderResponse() : StrategyParentOrderResponse(nullptr) {}
  ~StrategyParentOrderResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StrategyParentOrderResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StrategyParentOrderResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StrategyParentOrderResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline StrategyParentOrderResponse(const StrategyParentOrderResponse& from) : StrategyParentOrderResponse(nullptr, from) {}
  inline StrategyParentOrderResponse(StrategyParentOrderResponse&& from) noexcept
      : StrategyParentOrderResponse(nullptr, std::move(from)) {}
  inline StrategyParentOrderResponse& operator=(const StrategyParentOrderResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StrategyParentOrderResponse& operator=(StrategyParentOrderResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StrategyParentOrderResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const StrategyParentOrderResponse* internal_default_instance() {
    return reinterpret_cast<const StrategyParentOrderResponse*>(
        &_StrategyParentOrderResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(StrategyParentOrderResponse& a, StrategyParentOrderResponse& b) { a.Swap(&b); }
  inline void Swap(StrategyParentOrderResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StrategyParentOrderResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StrategyParentOrderResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StrategyParentOrderResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StrategyParentOrderResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StrategyParentOrderResponse& from) { StrategyParentOrderResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StrategyParentOrderResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "strategy.StrategyParentOrderResponse"; }

 protected:
  explicit StrategyParentOrderResponse(::google::protobuf::Arena* arena);
  StrategyParentOrderResponse(::google::protobuf::Arena* arena, const StrategyParentOrderResponse& from);
  StrategyParentOrderResponse(::google::protobuf::Arena* arena, StrategyParentOrderResponse&& from) noexcept
      : StrategyParentOrderResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message() ;
  const std::string& error_message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* value);

  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(
      const std::string& value);
  std::string* _internal_mutable_error_message();

  public:
  // .strategy.OrderStatus status = 1;
  void clear_status() ;
  ::strategy::OrderStatus status() const;
  void set_status(::strategy::OrderStatus value);

  private:
  ::strategy::OrderStatus _internal_status() const;
  void _internal_set_status(::strategy::OrderStatus value);

  public:
  // @@protoc_insertion_point(class_scope:strategy.StrategyParentOrderResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      58, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StrategyParentOrderResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    int status_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_strategy_5fparent_5forder_2eproto;
};
// -------------------------------------------------------------------

class StrategyParentOrderRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:strategy.StrategyParentOrderRequest) */ {
 public:
  inline StrategyParentOrderRequest() : StrategyParentOrderRequest(nullptr) {}
  ~StrategyParentOrderRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StrategyParentOrderRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StrategyParentOrderRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StrategyParentOrderRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline StrategyParentOrderRequest(const StrategyParentOrderRequest& from) : StrategyParentOrderRequest(nullptr, from) {}
  inline StrategyParentOrderRequest(StrategyParentOrderRequest&& from) noexcept
      : StrategyParentOrderRequest(nullptr, std::move(from)) {}
  inline StrategyParentOrderRequest& operator=(const StrategyParentOrderRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StrategyParentOrderRequest& operator=(StrategyParentOrderRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StrategyParentOrderRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StrategyParentOrderRequest* internal_default_instance() {
    return reinterpret_cast<const StrategyParentOrderRequest*>(
        &_StrategyParentOrderRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StrategyParentOrderRequest& a, StrategyParentOrderRequest& b) { a.Swap(&b); }
  inline void Swap(StrategyParentOrderRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StrategyParentOrderRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StrategyParentOrderRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StrategyParentOrderRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StrategyParentOrderRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StrategyParentOrderRequest& from) { StrategyParentOrderRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StrategyParentOrderRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "strategy.StrategyParentOrderRequest"; }

 protected:
  explicit StrategyParentOrderRequest(::google::protobuf::Arena* arena);
  StrategyParentOrderRequest(::google::protobuf::Arena* arena, const StrategyParentOrderRequest& from);
  StrategyParentOrderRequest(::google::protobuf::Arena* arena, StrategyParentOrderRequest&& from) noexcept
      : StrategyParentOrderRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSymbolFieldNumber = 1,
    kPriceFieldNumber = 2,
    kQuantityFieldNumber = 3,
  };
  // string symbol = 1;
  void clear_symbol() ;
  const std::string& symbol() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* value);

  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(
      const std::string& value);
  std::string* _internal_mutable_symbol();

  public:
  // double price = 2;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // double quantity = 3;
  void clear_quantity() ;
  double quantity() const;
  void set_quantity(double value);

  private:
  double _internal_quantity() const;
  void _internal_set_quantity(double value);

  public:
  // @@protoc_insertion_point(class_scope:strategy.StrategyParentOrderRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      50, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StrategyParentOrderRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    double price_;
    double quantity_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_strategy_5fparent_5forder_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StrategyParentOrderRequest

// string symbol = 1;
inline void StrategyParentOrderRequest::clear_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.ClearToEmpty();
}
inline const std::string& StrategyParentOrderRequest::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:strategy.StrategyParentOrderRequest.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StrategyParentOrderRequest::set_symbol(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:strategy.StrategyParentOrderRequest.symbol)
}
inline std::string* StrategyParentOrderRequest::mutable_symbol() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:strategy.StrategyParentOrderRequest.symbol)
  return _s;
}
inline const std::string& StrategyParentOrderRequest::_internal_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.symbol_.Get();
}
inline void StrategyParentOrderRequest::_internal_set_symbol(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.Set(value, GetArena());
}
inline std::string* StrategyParentOrderRequest::_internal_mutable_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.symbol_.Mutable( GetArena());
}
inline std::string* StrategyParentOrderRequest::release_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:strategy.StrategyParentOrderRequest.symbol)
  return _impl_.symbol_.Release();
}
inline void StrategyParentOrderRequest::set_allocated_symbol(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.symbol_.IsDefault()) {
    _impl_.symbol_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:strategy.StrategyParentOrderRequest.symbol)
}

// double price = 2;
inline void StrategyParentOrderRequest::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
}
inline double StrategyParentOrderRequest::price() const {
  // @@protoc_insertion_point(field_get:strategy.StrategyParentOrderRequest.price)
  return _internal_price();
}
inline void StrategyParentOrderRequest::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:strategy.StrategyParentOrderRequest.price)
}
inline double StrategyParentOrderRequest::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void StrategyParentOrderRequest::_internal_set_price(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// double quantity = 3;
inline void StrategyParentOrderRequest::clear_quantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_ = 0;
}
inline double StrategyParentOrderRequest::quantity() const {
  // @@protoc_insertion_point(field_get:strategy.StrategyParentOrderRequest.quantity)
  return _internal_quantity();
}
inline void StrategyParentOrderRequest::set_quantity(double value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:strategy.StrategyParentOrderRequest.quantity)
}
inline double StrategyParentOrderRequest::_internal_quantity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quantity_;
}
inline void StrategyParentOrderRequest::_internal_set_quantity(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_ = value;
}

// -------------------------------------------------------------------

// StrategyParentOrderResponse

// .strategy.OrderStatus status = 1;
inline void StrategyParentOrderResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
}
inline ::strategy::OrderStatus StrategyParentOrderResponse::status() const {
  // @@protoc_insertion_point(field_get:strategy.StrategyParentOrderResponse.status)
  return _internal_status();
}
inline void StrategyParentOrderResponse::set_status(::strategy::OrderStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:strategy.StrategyParentOrderResponse.status)
}
inline ::strategy::OrderStatus StrategyParentOrderResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::strategy::OrderStatus>(_impl_.status_);
}
inline void StrategyParentOrderResponse::_internal_set_status(::strategy::OrderStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string error_message = 2;
inline void StrategyParentOrderResponse::clear_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& StrategyParentOrderResponse::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:strategy.StrategyParentOrderResponse.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StrategyParentOrderResponse::set_error_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:strategy.StrategyParentOrderResponse.error_message)
}
inline std::string* StrategyParentOrderResponse::mutable_error_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:strategy.StrategyParentOrderResponse.error_message)
  return _s;
}
inline const std::string& StrategyParentOrderResponse::_internal_error_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_message_.Get();
}
inline void StrategyParentOrderResponse::_internal_set_error_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(value, GetArena());
}
inline std::string* StrategyParentOrderResponse::_internal_mutable_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_message_.Mutable( GetArena());
}
inline std::string* StrategyParentOrderResponse::release_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:strategy.StrategyParentOrderResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void StrategyParentOrderResponse::set_allocated_error_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:strategy.StrategyParentOrderResponse.error_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace strategy


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::strategy::OrderStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::strategy::OrderStatus>() {
  return ::strategy::OrderStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // strategy_5fparent_5forder_2eproto_2epb_2eh
