// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: strategy_control_request.proto

#include "pch.h"
#include "strategy_control_request.pb.h"
#include "strategy_control_request.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace strategy {

static const char* StrategyRequestService_method_names[] = {
  "/strategy.StrategyRequestService/ControlStrategy",
};

std::unique_ptr< StrategyRequestService::Stub> StrategyRequestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StrategyRequestService::Stub> stub(new StrategyRequestService::Stub(channel, options));
  return stub;
}

StrategyRequestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ControlStrategy_(StrategyRequestService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StrategyRequestService::Stub::ControlStrategy(::grpc::ClientContext* context, const ::strategy::StrategyRequest& request, ::strategy::StrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::strategy::StrategyRequest, ::strategy::StrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ControlStrategy_, context, request, response);
}

void StrategyRequestService::Stub::async::ControlStrategy(::grpc::ClientContext* context, const ::strategy::StrategyRequest* request, ::strategy::StrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::strategy::StrategyRequest, ::strategy::StrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ControlStrategy_, context, request, response, std::move(f));
}

void StrategyRequestService::Stub::async::ControlStrategy(::grpc::ClientContext* context, const ::strategy::StrategyRequest* request, ::strategy::StrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ControlStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::strategy::StrategyResponse>* StrategyRequestService::Stub::PrepareAsyncControlStrategyRaw(::grpc::ClientContext* context, const ::strategy::StrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::strategy::StrategyResponse, ::strategy::StrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ControlStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::strategy::StrategyResponse>* StrategyRequestService::Stub::AsyncControlStrategyRaw(::grpc::ClientContext* context, const ::strategy::StrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncControlStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

StrategyRequestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StrategyRequestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StrategyRequestService::Service, ::strategy::StrategyRequest, ::strategy::StrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StrategyRequestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::strategy::StrategyRequest* req,
             ::strategy::StrategyResponse* resp) {
               return service->ControlStrategy(ctx, req, resp);
             }, this)));
}

StrategyRequestService::Service::~Service() {
}

::grpc::Status StrategyRequestService::Service::ControlStrategy(::grpc::ServerContext* context, const ::strategy::StrategyRequest* request, ::strategy::StrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace strategy

