// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: strategy_control_request.proto
// Protobuf C++ Version: 5.29.2

#include "pch.h"

#include "strategy_control_request.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace strategy {

inline constexpr StrategyResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::strategy::RequestStatus >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StrategyResponse::StrategyResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StrategyResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StrategyResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StrategyResponseDefaultTypeInternal() {}
  union {
    StrategyResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StrategyResponseDefaultTypeInternal _StrategyResponse_default_instance_;

inline constexpr StrategyRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : strategy_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        live_trading_control_{static_cast< ::strategy::LiveTradingControl >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StrategyRequest::StrategyRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StrategyRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StrategyRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StrategyRequestDefaultTypeInternal() {}
  union {
    StrategyRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StrategyRequestDefaultTypeInternal _StrategyRequest_default_instance_;
}  // namespace strategy
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_strategy_5fcontrol_5frequest_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_strategy_5fcontrol_5frequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_strategy_5fcontrol_5frequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyRequest, _impl_.strategy_id_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyRequest, _impl_.live_trading_control_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyResponse, _impl_.error_message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::strategy::StrategyRequest)},
        {10, -1, -1, sizeof(::strategy::StrategyResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::strategy::_StrategyRequest_default_instance_._instance,
    &::strategy::_StrategyResponse_default_instance_._instance,
};
const char descriptor_table_protodef_strategy_5fcontrol_5frequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\036strategy_control_request.proto\022\010strate"
    "gy\"b\n\017StrategyRequest\022\023\n\013strategy_id\030\001 \001"
    "(\t\022:\n\024live_trading_control\030\002 \001(\0162\034.strat"
    "egy.LiveTradingControl\"R\n\020StrategyRespon"
    "se\022\'\n\006status\030\001 \001(\0162\027.strategy.RequestSta"
    "tus\022\025\n\rerror_message\030\002 \001(\t**\n\022LiveTradin"
    "gControl\022\010\n\004STOP\020\000\022\n\n\006RESUME\020\001*)\n\rReques"
    "tStatus\022\013\n\007SUCCESS\020\000\022\013\n\007FAILURE\020\0012b\n\026Str"
    "ategyRequestService\022H\n\017ControlStrategy\022\031"
    ".strategy.StrategyRequest\032\032.strategy.Str"
    "ategyResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_strategy_5fcontrol_5frequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_strategy_5fcontrol_5frequest_2eproto = {
    false,
    false,
    421,
    descriptor_table_protodef_strategy_5fcontrol_5frequest_2eproto,
    "strategy_control_request.proto",
    &descriptor_table_strategy_5fcontrol_5frequest_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_strategy_5fcontrol_5frequest_2eproto::offsets,
    file_level_enum_descriptors_strategy_5fcontrol_5frequest_2eproto,
    file_level_service_descriptors_strategy_5fcontrol_5frequest_2eproto,
};
namespace strategy {
const ::google::protobuf::EnumDescriptor* LiveTradingControl_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_strategy_5fcontrol_5frequest_2eproto);
  return file_level_enum_descriptors_strategy_5fcontrol_5frequest_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t LiveTradingControl_internal_data_[] = {
    131072u, 0u, };
bool LiveTradingControl_IsValid(int value) {
  return 0 <= value && value <= 1;
}
const ::google::protobuf::EnumDescriptor* RequestStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_strategy_5fcontrol_5frequest_2eproto);
  return file_level_enum_descriptors_strategy_5fcontrol_5frequest_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t RequestStatus_internal_data_[] = {
    131072u, 0u, };
bool RequestStatus_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class StrategyRequest::_Internal {
 public:
};

StrategyRequest::StrategyRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:strategy.StrategyRequest)
}
inline PROTOBUF_NDEBUG_INLINE StrategyRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::strategy::StrategyRequest& from_msg)
      : strategy_id_(arena, from.strategy_id_),
        _cached_size_{0} {}

StrategyRequest::StrategyRequest(
    ::google::protobuf::Arena* arena,
    const StrategyRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StrategyRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.live_trading_control_ = from._impl_.live_trading_control_;

  // @@protoc_insertion_point(copy_constructor:strategy.StrategyRequest)
}
inline PROTOBUF_NDEBUG_INLINE StrategyRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : strategy_id_(arena),
        _cached_size_{0} {}

inline void StrategyRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.live_trading_control_ = {};
}
StrategyRequest::~StrategyRequest() {
  // @@protoc_insertion_point(destructor:strategy.StrategyRequest)
  SharedDtor(*this);
}
inline void StrategyRequest::SharedDtor(MessageLite& self) {
  StrategyRequest& this_ = static_cast<StrategyRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.strategy_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* StrategyRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StrategyRequest(arena);
}
constexpr auto StrategyRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(StrategyRequest),
                                            alignof(StrategyRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StrategyRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StrategyRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StrategyRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StrategyRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StrategyRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StrategyRequest>(), &StrategyRequest::ByteSizeLong,
            &StrategyRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StrategyRequest, _impl_._cached_size_),
        false,
    },
    &StrategyRequest::kDescriptorMethods,
    &descriptor_table_strategy_5fcontrol_5frequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StrategyRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> StrategyRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::strategy::StrategyRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .strategy.LiveTradingControl live_trading_control = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StrategyRequest, _impl_.live_trading_control_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyRequest, _impl_.live_trading_control_)}},
    // string strategy_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyRequest, _impl_.strategy_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string strategy_id = 1;
    {PROTOBUF_FIELD_OFFSET(StrategyRequest, _impl_.strategy_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .strategy.LiveTradingControl live_trading_control = 2;
    {PROTOBUF_FIELD_OFFSET(StrategyRequest, _impl_.live_trading_control_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\30\13\0\0\0\0\0\0"
    "strategy.StrategyRequest"
    "strategy_id"
  }},
};

PROTOBUF_NOINLINE void StrategyRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:strategy.StrategyRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.strategy_id_.ClearToEmpty();
  _impl_.live_trading_control_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StrategyRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StrategyRequest& this_ = static_cast<const StrategyRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StrategyRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StrategyRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:strategy.StrategyRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string strategy_id = 1;
          if (!this_._internal_strategy_id().empty()) {
            const std::string& _s = this_._internal_strategy_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyRequest.strategy_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .strategy.LiveTradingControl live_trading_control = 2;
          if (this_._internal_live_trading_control() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_live_trading_control(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:strategy.StrategyRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StrategyRequest::ByteSizeLong(const MessageLite& base) {
          const StrategyRequest& this_ = static_cast<const StrategyRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StrategyRequest::ByteSizeLong() const {
          const StrategyRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:strategy.StrategyRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string strategy_id = 1;
            if (!this_._internal_strategy_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_strategy_id());
            }
            // .strategy.LiveTradingControl live_trading_control = 2;
            if (this_._internal_live_trading_control() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_live_trading_control());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StrategyRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StrategyRequest*>(&to_msg);
  auto& from = static_cast<const StrategyRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:strategy.StrategyRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_strategy_id().empty()) {
    _this->_internal_set_strategy_id(from._internal_strategy_id());
  }
  if (from._internal_live_trading_control() != 0) {
    _this->_impl_.live_trading_control_ = from._impl_.live_trading_control_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StrategyRequest::CopyFrom(const StrategyRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:strategy.StrategyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StrategyRequest::InternalSwap(StrategyRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.strategy_id_, &other->_impl_.strategy_id_, arena);
  swap(_impl_.live_trading_control_, other->_impl_.live_trading_control_);
}

::google::protobuf::Metadata StrategyRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StrategyResponse::_Internal {
 public:
};

StrategyResponse::StrategyResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:strategy.StrategyResponse)
}
inline PROTOBUF_NDEBUG_INLINE StrategyResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::strategy::StrategyResponse& from_msg)
      : error_message_(arena, from.error_message_),
        _cached_size_{0} {}

StrategyResponse::StrategyResponse(
    ::google::protobuf::Arena* arena,
    const StrategyResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StrategyResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:strategy.StrategyResponse)
}
inline PROTOBUF_NDEBUG_INLINE StrategyResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_message_(arena),
        _cached_size_{0} {}

inline void StrategyResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
StrategyResponse::~StrategyResponse() {
  // @@protoc_insertion_point(destructor:strategy.StrategyResponse)
  SharedDtor(*this);
}
inline void StrategyResponse::SharedDtor(MessageLite& self) {
  StrategyResponse& this_ = static_cast<StrategyResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* StrategyResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StrategyResponse(arena);
}
constexpr auto StrategyResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(StrategyResponse),
                                            alignof(StrategyResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StrategyResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StrategyResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StrategyResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StrategyResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StrategyResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StrategyResponse>(), &StrategyResponse::ByteSizeLong,
            &StrategyResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StrategyResponse, _impl_._cached_size_),
        false,
    },
    &StrategyResponse::kDescriptorMethods,
    &descriptor_table_strategy_5fcontrol_5frequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StrategyResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> StrategyResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::strategy::StrategyResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error_message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyResponse, _impl_.error_message_)}},
    // .strategy.RequestStatus status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StrategyResponse, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .strategy.RequestStatus status = 1;
    {PROTOBUF_FIELD_OFFSET(StrategyResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string error_message = 2;
    {PROTOBUF_FIELD_OFFSET(StrategyResponse, _impl_.error_message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\15\0\0\0\0\0"
    "strategy.StrategyResponse"
    "error_message"
  }},
};

PROTOBUF_NOINLINE void StrategyResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:strategy.StrategyResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StrategyResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StrategyResponse& this_ = static_cast<const StrategyResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StrategyResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StrategyResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:strategy.StrategyResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .strategy.RequestStatus status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_status(), target);
          }

          // string error_message = 2;
          if (!this_._internal_error_message().empty()) {
            const std::string& _s = this_._internal_error_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyResponse.error_message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:strategy.StrategyResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StrategyResponse::ByteSizeLong(const MessageLite& base) {
          const StrategyResponse& this_ = static_cast<const StrategyResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StrategyResponse::ByteSizeLong() const {
          const StrategyResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:strategy.StrategyResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string error_message = 2;
            if (!this_._internal_error_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_message());
            }
            // .strategy.RequestStatus status = 1;
            if (this_._internal_status() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StrategyResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StrategyResponse*>(&to_msg);
  auto& from = static_cast<const StrategyResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:strategy.StrategyResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StrategyResponse::CopyFrom(const StrategyResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:strategy.StrategyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StrategyResponse::InternalSwap(StrategyResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata StrategyResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace strategy
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_strategy_5fcontrol_5frequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
