// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: strategy_parent_order.proto

#include "pch.h"

#include "strategy_parent_order.pb.h"
#include "strategy_parent_order.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace strategy {

static const char* StrategyOrderService_method_names[] = {
  "/strategy.StrategyOrderService/SubmitParentOrder",
};

std::unique_ptr< StrategyOrderService::Stub> StrategyOrderService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StrategyOrderService::Stub> stub(new StrategyOrderService::Stub(channel, options));
  return stub;
}

StrategyOrderService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubmitParentOrder_(StrategyOrderService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StrategyOrderService::Stub::SubmitParentOrder(::grpc::ClientContext* context, const ::strategy::StrategyParentOrderRequest& request, ::strategy::StrategyParentOrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::strategy::StrategyParentOrderRequest, ::strategy::StrategyParentOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitParentOrder_, context, request, response);
}

void StrategyOrderService::Stub::async::SubmitParentOrder(::grpc::ClientContext* context, const ::strategy::StrategyParentOrderRequest* request, ::strategy::StrategyParentOrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::strategy::StrategyParentOrderRequest, ::strategy::StrategyParentOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitParentOrder_, context, request, response, std::move(f));
}

void StrategyOrderService::Stub::async::SubmitParentOrder(::grpc::ClientContext* context, const ::strategy::StrategyParentOrderRequest* request, ::strategy::StrategyParentOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitParentOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::strategy::StrategyParentOrderResponse>* StrategyOrderService::Stub::PrepareAsyncSubmitParentOrderRaw(::grpc::ClientContext* context, const ::strategy::StrategyParentOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::strategy::StrategyParentOrderResponse, ::strategy::StrategyParentOrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitParentOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::strategy::StrategyParentOrderResponse>* StrategyOrderService::Stub::AsyncSubmitParentOrderRaw(::grpc::ClientContext* context, const ::strategy::StrategyParentOrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitParentOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

StrategyOrderService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StrategyOrderService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StrategyOrderService::Service, ::strategy::StrategyParentOrderRequest, ::strategy::StrategyParentOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StrategyOrderService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::strategy::StrategyParentOrderRequest* req,
             ::strategy::StrategyParentOrderResponse* resp) {
               return service->SubmitParentOrder(ctx, req, resp);
             }, this)));
}

StrategyOrderService::Service::~Service() {
}

::grpc::Status StrategyOrderService::Service::SubmitParentOrder(::grpc::ServerContext* context, const ::strategy::StrategyParentOrderRequest* request, ::strategy::StrategyParentOrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace strategy

