// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: strategy_parent_order.proto
// Protobuf C++ Version: 5.29.2

#include "pch.h"

#include "strategy_parent_order.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace strategy {

inline constexpr StrategyParentOrderResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::strategy::OrderStatus >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StrategyParentOrderResponse::StrategyParentOrderResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StrategyParentOrderResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StrategyParentOrderResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StrategyParentOrderResponseDefaultTypeInternal() {}
  union {
    StrategyParentOrderResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StrategyParentOrderResponseDefaultTypeInternal _StrategyParentOrderResponse_default_instance_;

inline constexpr StrategyParentOrderRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        strategy_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        start_time_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        end_time_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        side_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        child_order_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        parent_order_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        parent_order_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        original_parent_order_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        price_{0},
        quantity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StrategyParentOrderRequest::StrategyParentOrderRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StrategyParentOrderRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StrategyParentOrderRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StrategyParentOrderRequestDefaultTypeInternal() {}
  union {
    StrategyParentOrderRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StrategyParentOrderRequestDefaultTypeInternal _StrategyParentOrderRequest_default_instance_;
}  // namespace strategy
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_strategy_5fparent_5forder_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_strategy_5fparent_5forder_2eproto = nullptr;
const ::uint32_t
    TableStruct_strategy_5fparent_5forder_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.quantity_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.strategy_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.start_time_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.end_time_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.side_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.child_order_type_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.parent_order_type_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.parent_order_id_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderRequest, _impl_.original_parent_order_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::strategy::StrategyParentOrderResponse, _impl_.error_message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::strategy::StrategyParentOrderRequest)},
        {19, -1, -1, sizeof(::strategy::StrategyParentOrderResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::strategy::_StrategyParentOrderRequest_default_instance_._instance,
    &::strategy::_StrategyParentOrderResponse_default_instance_._instance,
};
const char descriptor_table_protodef_strategy_5fparent_5forder_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033strategy_parent_order.proto\022\010strategy\""
    "\203\002\n\032StrategyParentOrderRequest\022\016\n\006symbol"
    "\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\001\022"
    "\020\n\010strategy\030\004 \001(\t\022\022\n\nstart_time\030\005 \001(\t\022\020\n"
    "\010end_time\030\006 \001(\t\022\014\n\004side\030\007 \001(\t\022\030\n\020child_o"
    "rder_type\030\010 \001(\t\022\031\n\021parent_order_type\030\t \001"
    "(\t\022\027\n\017parent_order_id\030\n \001(\t\022 \n\030original_"
    "parent_order_id\030\013 \001(\t\"[\n\033StrategyParentO"
    "rderResponse\022%\n\006status\030\001 \001(\0162\025.strategy."
    "OrderStatus\022\025\n\rerror_message\030\002 \001(\t*2\n\013Or"
    "derStatus\022\021\n\rORDER_SUCCESS\020\000\022\020\n\014ORDER_FA"
    "ILED\020\0012x\n\024StrategyOrderService\022`\n\021Submit"
    "ParentOrder\022$.strategy.StrategyParentOrd"
    "erRequest\032%.strategy.StrategyParentOrder"
    "Responseb\006proto3"
};
static ::absl::once_flag descriptor_table_strategy_5fparent_5forder_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_strategy_5fparent_5forder_2eproto = {
    false,
    false,
    576,
    descriptor_table_protodef_strategy_5fparent_5forder_2eproto,
    "strategy_parent_order.proto",
    &descriptor_table_strategy_5fparent_5forder_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_strategy_5fparent_5forder_2eproto::offsets,
    file_level_enum_descriptors_strategy_5fparent_5forder_2eproto,
    file_level_service_descriptors_strategy_5fparent_5forder_2eproto,
};
namespace strategy {
const ::google::protobuf::EnumDescriptor* OrderStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_strategy_5fparent_5forder_2eproto);
  return file_level_enum_descriptors_strategy_5fparent_5forder_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t OrderStatus_internal_data_[] = {
    131072u, 0u, };
bool OrderStatus_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class StrategyParentOrderRequest::_Internal {
 public:
};

StrategyParentOrderRequest::StrategyParentOrderRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:strategy.StrategyParentOrderRequest)
}
inline PROTOBUF_NDEBUG_INLINE StrategyParentOrderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::strategy::StrategyParentOrderRequest& from_msg)
      : symbol_(arena, from.symbol_),
        strategy_(arena, from.strategy_),
        start_time_(arena, from.start_time_),
        end_time_(arena, from.end_time_),
        side_(arena, from.side_),
        child_order_type_(arena, from.child_order_type_),
        parent_order_type_(arena, from.parent_order_type_),
        parent_order_id_(arena, from.parent_order_id_),
        original_parent_order_id_(arena, from.original_parent_order_id_),
        _cached_size_{0} {}

StrategyParentOrderRequest::StrategyParentOrderRequest(
    ::google::protobuf::Arena* arena,
    const StrategyParentOrderRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StrategyParentOrderRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, price_),
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::quantity_));

  // @@protoc_insertion_point(copy_constructor:strategy.StrategyParentOrderRequest)
}
inline PROTOBUF_NDEBUG_INLINE StrategyParentOrderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : symbol_(arena),
        strategy_(arena),
        start_time_(arena),
        end_time_(arena),
        side_(arena),
        child_order_type_(arena),
        parent_order_type_(arena),
        parent_order_id_(arena),
        original_parent_order_id_(arena),
        _cached_size_{0} {}

inline void StrategyParentOrderRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::quantity_));
}
StrategyParentOrderRequest::~StrategyParentOrderRequest() {
  // @@protoc_insertion_point(destructor:strategy.StrategyParentOrderRequest)
  SharedDtor(*this);
}
inline void StrategyParentOrderRequest::SharedDtor(MessageLite& self) {
  StrategyParentOrderRequest& this_ = static_cast<StrategyParentOrderRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.symbol_.Destroy();
  this_._impl_.strategy_.Destroy();
  this_._impl_.start_time_.Destroy();
  this_._impl_.end_time_.Destroy();
  this_._impl_.side_.Destroy();
  this_._impl_.child_order_type_.Destroy();
  this_._impl_.parent_order_type_.Destroy();
  this_._impl_.parent_order_id_.Destroy();
  this_._impl_.original_parent_order_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* StrategyParentOrderRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StrategyParentOrderRequest(arena);
}
constexpr auto StrategyParentOrderRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(StrategyParentOrderRequest),
                                            alignof(StrategyParentOrderRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StrategyParentOrderRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StrategyParentOrderRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StrategyParentOrderRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StrategyParentOrderRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StrategyParentOrderRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StrategyParentOrderRequest>(), &StrategyParentOrderRequest::ByteSizeLong,
            &StrategyParentOrderRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_._cached_size_),
        false,
    },
    &StrategyParentOrderRequest::kDescriptorMethods,
    &descriptor_table_strategy_5fparent_5forder_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StrategyParentOrderRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 0, 160, 2> StrategyParentOrderRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::strategy::StrategyParentOrderRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string symbol = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.symbol_)}},
    // double price = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.price_)}},
    // double quantity = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.quantity_)}},
    // string strategy = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.strategy_)}},
    // string start_time = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.start_time_)}},
    // string end_time = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.end_time_)}},
    // string side = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.side_)}},
    // string child_order_type = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.child_order_type_)}},
    // string parent_order_type = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.parent_order_type_)}},
    // string parent_order_id = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.parent_order_id_)}},
    // string original_parent_order_id = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.original_parent_order_id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string symbol = 1;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.symbol_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double price = 2;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double quantity = 3;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.quantity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string strategy = 4;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.strategy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string start_time = 5;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.start_time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string end_time = 6;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.end_time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string side = 7;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.side_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string child_order_type = 8;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.child_order_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string parent_order_type = 9;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.parent_order_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string parent_order_id = 10;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.parent_order_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string original_parent_order_id = 11;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.original_parent_order_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\6\0\0\10\12\10\4\20\21\17\30\0\0\0\0"
    "strategy.StrategyParentOrderRequest"
    "symbol"
    "strategy"
    "start_time"
    "end_time"
    "side"
    "child_order_type"
    "parent_order_type"
    "parent_order_id"
    "original_parent_order_id"
  }},
};

PROTOBUF_NOINLINE void StrategyParentOrderRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:strategy.StrategyParentOrderRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.symbol_.ClearToEmpty();
  _impl_.strategy_.ClearToEmpty();
  _impl_.start_time_.ClearToEmpty();
  _impl_.end_time_.ClearToEmpty();
  _impl_.side_.ClearToEmpty();
  _impl_.child_order_type_.ClearToEmpty();
  _impl_.parent_order_type_.ClearToEmpty();
  _impl_.parent_order_id_.ClearToEmpty();
  _impl_.original_parent_order_id_.ClearToEmpty();
  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.quantity_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.quantity_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StrategyParentOrderRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StrategyParentOrderRequest& this_ = static_cast<const StrategyParentOrderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StrategyParentOrderRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StrategyParentOrderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:strategy.StrategyParentOrderRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string symbol = 1;
          if (!this_._internal_symbol().empty()) {
            const std::string& _s = this_._internal_symbol();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.symbol");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double price = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_price(), target);
          }

          // double quantity = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_quantity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_quantity(), target);
          }

          // string strategy = 4;
          if (!this_._internal_strategy().empty()) {
            const std::string& _s = this_._internal_strategy();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.strategy");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string start_time = 5;
          if (!this_._internal_start_time().empty()) {
            const std::string& _s = this_._internal_start_time();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.start_time");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // string end_time = 6;
          if (!this_._internal_end_time().empty()) {
            const std::string& _s = this_._internal_end_time();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.end_time");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // string side = 7;
          if (!this_._internal_side().empty()) {
            const std::string& _s = this_._internal_side();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.side");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // string child_order_type = 8;
          if (!this_._internal_child_order_type().empty()) {
            const std::string& _s = this_._internal_child_order_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.child_order_type");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          // string parent_order_type = 9;
          if (!this_._internal_parent_order_type().empty()) {
            const std::string& _s = this_._internal_parent_order_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.parent_order_type");
            target = stream->WriteStringMaybeAliased(9, _s, target);
          }

          // string parent_order_id = 10;
          if (!this_._internal_parent_order_id().empty()) {
            const std::string& _s = this_._internal_parent_order_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.parent_order_id");
            target = stream->WriteStringMaybeAliased(10, _s, target);
          }

          // string original_parent_order_id = 11;
          if (!this_._internal_original_parent_order_id().empty()) {
            const std::string& _s = this_._internal_original_parent_order_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderRequest.original_parent_order_id");
            target = stream->WriteStringMaybeAliased(11, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:strategy.StrategyParentOrderRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StrategyParentOrderRequest::ByteSizeLong(const MessageLite& base) {
          const StrategyParentOrderRequest& this_ = static_cast<const StrategyParentOrderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StrategyParentOrderRequest::ByteSizeLong() const {
          const StrategyParentOrderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:strategy.StrategyParentOrderRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string symbol = 1;
            if (!this_._internal_symbol().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_symbol());
            }
            // string strategy = 4;
            if (!this_._internal_strategy().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_strategy());
            }
            // string start_time = 5;
            if (!this_._internal_start_time().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_start_time());
            }
            // string end_time = 6;
            if (!this_._internal_end_time().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_end_time());
            }
            // string side = 7;
            if (!this_._internal_side().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_side());
            }
            // string child_order_type = 8;
            if (!this_._internal_child_order_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_child_order_type());
            }
            // string parent_order_type = 9;
            if (!this_._internal_parent_order_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_parent_order_type());
            }
            // string parent_order_id = 10;
            if (!this_._internal_parent_order_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_parent_order_id());
            }
            // string original_parent_order_id = 11;
            if (!this_._internal_original_parent_order_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_original_parent_order_id());
            }
            // double price = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
              total_size += 9;
            }
            // double quantity = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_quantity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StrategyParentOrderRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StrategyParentOrderRequest*>(&to_msg);
  auto& from = static_cast<const StrategyParentOrderRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:strategy.StrategyParentOrderRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_symbol().empty()) {
    _this->_internal_set_symbol(from._internal_symbol());
  }
  if (!from._internal_strategy().empty()) {
    _this->_internal_set_strategy(from._internal_strategy());
  }
  if (!from._internal_start_time().empty()) {
    _this->_internal_set_start_time(from._internal_start_time());
  }
  if (!from._internal_end_time().empty()) {
    _this->_internal_set_end_time(from._internal_end_time());
  }
  if (!from._internal_side().empty()) {
    _this->_internal_set_side(from._internal_side());
  }
  if (!from._internal_child_order_type().empty()) {
    _this->_internal_set_child_order_type(from._internal_child_order_type());
  }
  if (!from._internal_parent_order_type().empty()) {
    _this->_internal_set_parent_order_type(from._internal_parent_order_type());
  }
  if (!from._internal_parent_order_id().empty()) {
    _this->_internal_set_parent_order_id(from._internal_parent_order_id());
  }
  if (!from._internal_original_parent_order_id().empty()) {
    _this->_internal_set_original_parent_order_id(from._internal_original_parent_order_id());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_price()) != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_quantity()) != 0) {
    _this->_impl_.quantity_ = from._impl_.quantity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StrategyParentOrderRequest::CopyFrom(const StrategyParentOrderRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:strategy.StrategyParentOrderRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StrategyParentOrderRequest::InternalSwap(StrategyParentOrderRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.strategy_, &other->_impl_.strategy_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.start_time_, &other->_impl_.start_time_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.end_time_, &other->_impl_.end_time_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.side_, &other->_impl_.side_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.child_order_type_, &other->_impl_.child_order_type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.parent_order_type_, &other->_impl_.parent_order_type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.parent_order_id_, &other->_impl_.parent_order_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.original_parent_order_id_, &other->_impl_.original_parent_order_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.quantity_)
      + sizeof(StrategyParentOrderRequest::_impl_.quantity_)
      - PROTOBUF_FIELD_OFFSET(StrategyParentOrderRequest, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata StrategyParentOrderRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StrategyParentOrderResponse::_Internal {
 public:
};

StrategyParentOrderResponse::StrategyParentOrderResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:strategy.StrategyParentOrderResponse)
}
inline PROTOBUF_NDEBUG_INLINE StrategyParentOrderResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::strategy::StrategyParentOrderResponse& from_msg)
      : error_message_(arena, from.error_message_),
        _cached_size_{0} {}

StrategyParentOrderResponse::StrategyParentOrderResponse(
    ::google::protobuf::Arena* arena,
    const StrategyParentOrderResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StrategyParentOrderResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:strategy.StrategyParentOrderResponse)
}
inline PROTOBUF_NDEBUG_INLINE StrategyParentOrderResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_message_(arena),
        _cached_size_{0} {}

inline void StrategyParentOrderResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
StrategyParentOrderResponse::~StrategyParentOrderResponse() {
  // @@protoc_insertion_point(destructor:strategy.StrategyParentOrderResponse)
  SharedDtor(*this);
}
inline void StrategyParentOrderResponse::SharedDtor(MessageLite& self) {
  StrategyParentOrderResponse& this_ = static_cast<StrategyParentOrderResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* StrategyParentOrderResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StrategyParentOrderResponse(arena);
}
constexpr auto StrategyParentOrderResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(StrategyParentOrderResponse),
                                            alignof(StrategyParentOrderResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StrategyParentOrderResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StrategyParentOrderResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StrategyParentOrderResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StrategyParentOrderResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StrategyParentOrderResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StrategyParentOrderResponse>(), &StrategyParentOrderResponse::ByteSizeLong,
            &StrategyParentOrderResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StrategyParentOrderResponse, _impl_._cached_size_),
        false,
    },
    &StrategyParentOrderResponse::kDescriptorMethods,
    &descriptor_table_strategy_5fparent_5forder_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StrategyParentOrderResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 58, 2> StrategyParentOrderResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::strategy::StrategyParentOrderResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error_message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderResponse, _impl_.error_message_)}},
    // .strategy.OrderStatus status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StrategyParentOrderResponse, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StrategyParentOrderResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .strategy.OrderStatus status = 1;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string error_message = 2;
    {PROTOBUF_FIELD_OFFSET(StrategyParentOrderResponse, _impl_.error_message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\44\0\15\0\0\0\0\0"
    "strategy.StrategyParentOrderResponse"
    "error_message"
  }},
};

PROTOBUF_NOINLINE void StrategyParentOrderResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:strategy.StrategyParentOrderResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StrategyParentOrderResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StrategyParentOrderResponse& this_ = static_cast<const StrategyParentOrderResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StrategyParentOrderResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StrategyParentOrderResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:strategy.StrategyParentOrderResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .strategy.OrderStatus status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_status(), target);
          }

          // string error_message = 2;
          if (!this_._internal_error_message().empty()) {
            const std::string& _s = this_._internal_error_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "strategy.StrategyParentOrderResponse.error_message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:strategy.StrategyParentOrderResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StrategyParentOrderResponse::ByteSizeLong(const MessageLite& base) {
          const StrategyParentOrderResponse& this_ = static_cast<const StrategyParentOrderResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StrategyParentOrderResponse::ByteSizeLong() const {
          const StrategyParentOrderResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:strategy.StrategyParentOrderResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string error_message = 2;
            if (!this_._internal_error_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_message());
            }
            // .strategy.OrderStatus status = 1;
            if (this_._internal_status() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StrategyParentOrderResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StrategyParentOrderResponse*>(&to_msg);
  auto& from = static_cast<const StrategyParentOrderResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:strategy.StrategyParentOrderResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StrategyParentOrderResponse::CopyFrom(const StrategyParentOrderResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:strategy.StrategyParentOrderResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StrategyParentOrderResponse::InternalSwap(StrategyParentOrderResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata StrategyParentOrderResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace strategy
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_strategy_5fparent_5forder_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
